/**
 * `jevcode completion bash|zsh|fish` (TUI-DESIGN §17 item 4, D14): a **static** completion script generated from
 * `cli/args.ts` `FLAGS` + `COMMANDS` — the same text `scripts/gen-docs.mjs` writes to `completions/jevcode.*`
 * (the sync test diffs the two, so the shipped command and the committed files can never drift). Run-id completion
 * is shell-side (`ls ${JEVCODE_HOME:-$HOME/.jevcode}/runs`); destinations are printed in the header, never written.
 */
import type { CompletionShell } from './args.js';
import { COMMANDS as CLI_COMMANDS, FLAGS, type Command } from './args.js';

const ENUM_ARG_RE = /^[a-z0-9-]+(\|[a-z0-9-]+)+$/;

/** one-line descriptions of the CLI commands (zsh/fish `-d`) */
export const CLI_DESCRIPTIONS: Readonly<Record<Command, string>> = {
  chat: 'interactive session',
  run: 'run one task',
  config: 'print the resolved configuration',
  bench: 'run the benchmark suites',
  perf: 'run the performance gates',
  login: 'store an API key',
  logout: 'remove a stored API key',
  sessions: 'list or maintain sessions',
  // TUI-DESIGN-5 §6.6 (R5-6): `CLI_DESCRIPTIONS` is a TOTAL `Record<Command, string>`, so a new `Command` member
  // is a compile error here until its row lands — the same forced one-line edit W0 made in the two `theme*.test.ts`
  // literals for `UiLabel += '[session]'`.
  models: 'browse the model catalogue',
  // TUI-DESIGN-5 §5.5 (R5-5) / §4.2 (R5-4): the same forced one-line edit, one per new `Command` member
  import: 'import memory and workflows from other agents',
  agents: 'list the agents of a run',
  doctor: 'check this machine and print one fix per problem',
  report: 'write a support bundle',
  why: 'explain a Jev decision',
  calibration: 'reliability report',
  completion: 'print a completion script',
  upgrade: 'upgrade jevcode',
};

/** single-quote for sh (`'` → `'\''`) */
export function shQuote(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}

/** the visible flags of one command, in FLAGS order */
export function flagsFor(command: Command): (typeof FLAGS)[number][] {
  return FLAGS.filter((f) => f.commands.includes(command) && !f.hidden);
}

/** `completions/jevcode.bash` */
export function renderBash(): string {
  const L: string[] = ['# bash completion for jevcode — generated by scripts/gen-docs.mjs from src/cli/args.ts; do not edit by hand', '# install: jevcode completion bash > ~/.local/share/bash-completion/completions/jevcode', ''];
  L.push('_jevcode() {', '  local cur prev cmd words', '  COMPREPLY=()', '  cur="${COMP_WORDS[COMP_CWORD]}"', '  prev="${COMP_WORDS[COMP_CWORD-1]}"', '  cmd=""', '  local i', '  for ((i = 1; i < COMP_CWORD; i++)); do', '    case "${COMP_WORDS[i]}" in', `      ${CLI_COMMANDS.join('|')}) cmd="\${COMP_WORDS[i]}"; break ;;`, '    esac', '  done');
  L.push('  case "$prev" in', '    --resume)', '      local runs="${JEVCODE_HOME:-$HOME/.jevcode}/runs"', '      [ -d "$runs" ] && COMPREPLY=( $(compgen -W "$(ls "$runs" 2>/dev/null)" -- "$cur") )', '      return 0 ;;');
  const enums = new Map<string, string[]>();
  for (const f of FLAGS) if (!f.hidden && f.arg !== undefined && ENUM_ARG_RE.test(f.arg)) enums.set(f.name, f.arg.split('|'));
  for (const [name, values] of enums) L.push(`    --${name}) COMPREPLY=( $(compgen -W ${shQuote(values.join(' '))} -- "$cur") ); return 0 ;;`);
  L.push('    --task-file|--config|--out|--extra-env-file) COMPREPLY=( $(compgen -f -- "$cur") ); return 0 ;;', '    --workspace|--runs-dir) COMPREPLY=( $(compgen -d -- "$cur") ); return 0 ;;', '  esac');
  L.push('  if [ -z "$cmd" ]; then', `    COMPREPLY=( $(compgen -W ${shQuote([...CLI_COMMANDS, '--help', '--version'].join(' '))} -- "$cur") )`, '    return 0', '  fi', '  case "$cmd" in');
  for (const c of CLI_COMMANDS) L.push(`    ${c}) COMPREPLY=( $(compgen -W ${shQuote(flagsFor(c).map((f) => `--${f.name}`).join(' '))} -- "$cur") ) ;;`);
  L.push('  esac', '  return 0', '}', 'complete -F _jevcode jevcode', '');
  return L.join('\n');
}

/** `completions/jevcode.zsh` */
export function renderZsh(): string {
  const L: string[] = ['#compdef jevcode', '# zsh completion for jevcode — generated by scripts/gen-docs.mjs from src/cli/args.ts; do not edit by hand', '# install: jevcode completion zsh > ~/.zsh/completions/_jevcode  (with fpath+=~/.zsh/completions)', ''];
  L.push('_jevcode_runs() {', '  local runs="${JEVCODE_HOME:-$HOME/.jevcode}/runs"', '  [[ -d "$runs" ]] && _values "run id" ${runs}/*(N:t)', '}', '');
  L.push('_jevcode() {', '  local -a commands', '  commands=(');
  for (const c of CLI_COMMANDS) L.push(`    ${shQuote(`${c}:${CLI_DESCRIPTIONS[c]}`)}`);
  L.push('  )', '  _arguments -C \\', `    '1:command:->cmd' \\`, `    '*::arg:->args'`, '  case "$state" in', '    cmd) _describe -t commands "jevcode command" commands ;;', '    args)', '      case "${words[1]}" in');
  for (const c of CLI_COMMANDS) {
    L.push(`        ${c})`, '          _arguments \\');
    const specs = flagsFor(c).map((f) => {
      let action = '';
      // TUI-DESIGN-2 §1.4: a per-command value list (`--jev-provider typesafe|openrouter` on login) narrows the enum, as in scripts/gen-docs.mjs
      const arg = f.argFor?.[c] ?? f.arg;
      if (f.name === 'resume') action = ':run id:_jevcode_runs';
      else if (arg !== undefined && ENUM_ARG_RE.test(arg)) action = `:${f.name}:(${arg.split('|').join(' ')})`;
      else if (/file|path|config|out/.test(f.name)) action = `:${f.arg ?? 'file'}:_files`;
      else if (/dir|workspace/.test(f.name)) action = `:${f.arg ?? 'dir'}:_files -/`;
      else if (f.arg !== undefined) action = `:${f.arg.replace(/[<>]/g, '')}:`;
      return `            ${shQuote(`--${f.name}[${f.help.replace(/[[\]]/g, ' ')}]${action}`)}`;
    });
    L.push(specs.join(' \\\n') + (c === 'run' ? ` \\\n            '*:task text:'` : ''), '          ;;');
  }
  L.push('      esac ;;', '  esac', '}', '', '_jevcode "$@"', '');
  return L.join('\n');
}

/** `completions/jevcode.fish` */
export function renderFish(): string {
  const L: string[] = ['# fish completion for jevcode — generated by scripts/gen-docs.mjs from src/cli/args.ts; do not edit by hand', '# install: jevcode completion fish > ~/.config/fish/completions/jevcode.fish', ''];
  L.push('function __jevcode_runs', '  set -l runs (set -q JEVCODE_HOME; and echo $JEVCODE_HOME; or echo $HOME/.jevcode)/runs', '  test -d $runs; and ls $runs', 'end', '');
  L.push('complete -c jevcode -f');
  for (const c of CLI_COMMANDS) L.push(`complete -c jevcode -n '__fish_use_subcommand' -a ${c} -d ${shQuote(CLI_DESCRIPTIONS[c])}`);
  for (const f of FLAGS) {
    if (f.hidden) continue;
    const cond = `__fish_seen_subcommand_from ${f.commands.join(' ')}`;
    let extra = '';
    if (f.type === 'string') {
      if (f.name === 'resume') extra = ` -x -a '(__jevcode_runs)'`;
      else if (f.arg !== undefined && ENUM_ARG_RE.test(f.arg)) extra = ` -x -a ${shQuote(f.arg.split('|').join(' '))}`;
      else if (/file|config|out/.test(f.name)) extra = ' -r -F';
      else if (/dir|workspace/.test(f.name)) extra = " -x -a '(__fish_complete_directories)'";
      else extra = ' -x';
    }
    L.push(`complete -c jevcode -n ${shQuote(cond)} -l ${f.name}${extra} -d ${shQuote(f.help)}`);
  }
  L.push('');
  return L.join('\n');
}

/** TUI-DESIGN §17 item 4: the script for one shell. */
export function completionScript(shell: CompletionShell): string {
  switch (shell) {
    case 'bash':
      return renderBash();
    case 'zsh':
      return renderZsh();
    case 'fish':
      return renderFish();
  }
}

/** `jevcode completion <shell>`: print the script; exit 0. */
export function commandCompletion(shell: CompletionShell, out: { write(s: string): unknown }): number {
  out.write(completionScript(shell));
  return 0;
}
