# BEGIN-REPO-ONLY
# Canonical formula for the tap coasty-ai/homebrew-jevcode (`brew install coasty-ai/jevcode/jevcode`).
# scripts/release/render-packaging.mjs rewrites the `url` and `sha256` lines and removes this block; the
# release workflow validates the rendered file (install, test, audit, style) and pushes it to the tap.
# PLACEHOLDER: `url` names version 0.0.0 and `sha256` is not a digest, so this copy never installs.
# Node: package.json `engines` is `>=22.12.0` with no upper bound, so homebrew-core's current node fits.
# END-REPO-ONLY
# Generated from Formula/jevcode.rb in https://github.com/coasty-ai/JevCode; edit it there.
class Jevcode < Formula
  desc "Terminal coding agent that edits your code and verifies it with your tests"
  homepage "https://github.com/coasty-ai/JevCode"
  url "https://registry.npmjs.org/jevcode/-/jevcode-0.0.0.tgz"
  sha256 "PLACEHOLDER_SHA256_OF_THE_NPM_TARBALL_REPLACED_BY_THE_RELEASE_JOB" # PLACEHOLDER
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")

    # Man page and static completions ship in the tarball (generated by scripts/gen-docs.mjs).
    pkg = libexec/"lib/node_modules/jevcode"
    man1.install pkg/"man/jevcode.1"
    bash_completion.install pkg/"completions/jevcode.bash" => "jevcode"
    zsh_completion.install pkg/"completions/jevcode.zsh" => "_jevcode"
    fish_completion.install pkg/"completions/jevcode.fish"
  end

  test do
    assert_match "jevcode #{version}", shell_output("#{bin}/jevcode --version")
    assert_match "jevcode", shell_output("#{bin}/jevcode --help")
    assert_path_exists man1/"jevcode.1"
    assert_path_exists bash_completion/"jevcode"
    assert_path_exists zsh_completion/"_jevcode"
    assert_path_exists fish_completion/"jevcode.fish"
  end
end
