/**
 * JevCode shared contract (DESIGN.md §4, frozen for parallel implementation).
 *
 * Every module imports from here and from ../errors.ts. Implementers do not edit this file;
 * needed changes are reported back and reconciled centrally. Function declarations at the
 * bottom name the factory each module must export, so wiring code (cli/main.tsx) and the
 * bench can be written against this file alone.
 */

export type Json = string | number | boolean | null | Json[] | { [k: string]: Json };
export type JsonObject = { [k: string]: Json };

// ---------------------------------------------------------------------------------------
// Generator actions (the only thing the generator produces)
// ---------------------------------------------------------------------------------------

export type Action =
  | { kind: 'read'; paths: string[] } // show files, bounded
  | { kind: 'edit'; path: string; old: string; new: string } // exact, unique match
  | { kind: 'write'; path: string; content: string } // create or overwrite
  | { kind: 'patch'; diff: string } // unified diff, -p1, applied with git apply
  | { kind: 'run'; command: string; timeoutMs?: number } // sh -c in sandbox
  | { kind: 'done'; summary: string }; // proposal to finish

export type ActionKind = Action['kind'];

export interface PlanDraft {
  done: string[];
  remaining: string[];
  openProblems: string[];
}

export interface Proposal {
  goal: string;
  action: Action;
  plan: PlanDraft;
  /** Full assistant text (streamed text plus, for tool calls, the raw JSON input). Redacted. */
  rawText: string;
}

// ---------------------------------------------------------------------------------------
// Persistent plan
// ---------------------------------------------------------------------------------------

export interface PlanItemDone {
  text: string;
  /** judged -1 = not judged (jev-off). */
  evidence: { step: number; judged: number };
}
export interface PlanUnverified {
  text: string;
  step: number;
  judged: number;
}
export type HarnessProblemKind = 'replan' | 'rejected_claim' | 'stale_plan';
export interface HarnessProblem {
  kind: HarnessProblemKind;
  text: string;
  step: number;
}
export interface Plan {
  done: PlanItemDone[];
  remaining: string[];
  /** claimed, done_<j> in [0.3, 0.7), still in remaining */
  unverified: PlanUnverified[];
  /** generator entries, replaced each step */
  openProblems: string[];
  /** harness-owned (§6 Plan) */
  harnessProblems: HarnessProblem[];
}

// ---------------------------------------------------------------------------------------
// Execution
// ---------------------------------------------------------------------------------------

export type KilledBy = 'timeout' | 'wall_time' | 'abort' | null;

export interface ExecResult {
  /** exitCode === 0 && killedBy === null */
  ok: boolean;
  exitCode: number | null;
  signal: string | null;
  /** head (<= maxOutputBytes) + rolling tail (16 KB); see §8 */
  stdout: string;
  stderr: string;
  /** output cap passed; never a kill, never an error */
  truncated: boolean;
  bytesSeen: number;
  /** set by the code path that kills, before signalling */
  killedBy: KilledBy;
  /** derived: killedBy === 'timeout' */
  timedOut: boolean;
  /** pids from the kill snapshot still alive after SIGKILL (§8) */
  orphans: number[];
  /** sandbox-exec itself failed to exec the binary (exit 71) */
  sandboxExecDenied: boolean;
  durationMs: number;
}

export type ActionOutcome =
  | { status: 'executed'; exec?: ExecResult; summary: string; changedFiles: string[] }
  | { status: 'noop'; summary: string } // `done` proposal that passed risk
  | { status: 'blocked'; reason: string }
  | { status: 'declined'; reason: string } // confirmer returned false at review
  | { status: 'failed'; error: string } // patch did not apply, path escape, stage failure
  | { status: 'interrupted'; exec?: ExecResult }; // harness cancelled execute

export type OutcomeStatus = ActionOutcome['status'];

// ---------------------------------------------------------------------------------------
// Jev wire types
// ---------------------------------------------------------------------------------------

export interface NoulCriteria {
  true: Json;
  false: Json;
}
export type Question =
  | { type: 'noul'; instructions: Json; criteria?: NoulCriteria } // criteria omitted only for context Nouls (§5.5)
  | { type: 'choice'; instructions: Json; criteria: Record<string, Json | null> }
  | { type: 'score'; instructions: Json; criteria: Json[] };
export type QuestionType = Question['type'];

export type Answer =
  | { type: 'noul'; noul: number }
  | { type: 'choice'; choice: string; probabilities: Record<string, number>; confidence: number }
  | { type: 'score'; score: number; legend: Record<string, Json>; probabilities: Record<string, number>; confidence: number };

export interface JevRequest {
  model: string;
  state: Json;
  questions: Record<string, Question>;
}
export interface JevUsage {
  input_tokens: number;
  output_tokens: number;
  cost: number;
}
export interface JevResponse {
  model: string;
  answers: Record<string, Answer>;
  usage: JevUsage;
  id?: string;
  provider?: string;
}

export type StageName = 'replan' | 'intent' | 'context' | 'propose' | 'risk' | 'execute' | 'judge' | 'complete';

export type DecisionVerdict = 'ok' | 'review' | 'block' | 'chosen' | 'overridden' | 'fallback';

/** One row in the decisions pane and decisions.jsonl. */
export interface Decision {
  step: number;
  stage: StageName;
  id: string;
  question: Question;
  answer: Answer;
  /** P(chosen): noul p, choice probabilities[choice], score p_{k*} */
  probability: number;
  /** harness-computed (§5.3); for Nouls the derived |2p − 1| */
  confidence: number;
  /** risk: ok/review/block; intent, replan: chosen/overridden/fallback */
  verdict?: DecisionVerdict;
  /** the parent request's latency; display only */
  latencyMs: number;
  requestHash: string;
  /** only when it differs from the configured id (§5.4 rule 7) */
  servedModel?: string;
}

/** One per Decider.ask() call (jev.jsonl); the metric source for Jev latency. */
export interface JevRequestRecord {
  step: number;
  stage: StageName;
  requestHash: string;
  latencyMs: number;
  questions: number;
  usage: TokenUsage;
  model: string;
  attempts: number;
}

// ---------------------------------------------------------------------------------------
// Loop
// ---------------------------------------------------------------------------------------

/** What the generator sees (effective intent). */
export type Intent = 'investigate' | 'edit' | 'verify' | 'fix_environment' | 'finish';
/** What Jev may answer. */
export type IntentAnswer = Intent | 'none_of_these';

export type StopReason =
  | 'complete'
  | 'max_steps'
  | 'spend_cap'
  | 'wall_time'
  | 'max_replans'
  | 'human_abort'
  | 'signal'
  | 'replan_stop'
  | 'impossible'
  | 'generator_done' // Jev-off only
  | 'error';

export type ReplanMove = 'change_approach' | 'gather_context' | 'fix_environment' | 'revert_changes' | 'stop_and_report' | 'none_of_these';

export interface ReplanDirective {
  move: ReplanMove;
  probability: number;
  confidence: number;
  taskImpossible: number;
  text: string;
}

export type RiskDimension = 'destructive' | 'out_of_scope' | 'plan_mismatch' | 'irreversible';
export const RISK_DIMENSIONS: readonly RiskDimension[] = ['destructive', 'out_of_scope', 'plan_mismatch', 'irreversible'];

export interface RiskDimensionResult {
  risk: number;
  /** P(argmax level) */
  probability: number;
  expected: number;
  tailMass: number;
  bound: 'expected' | 'tail';
  confidence: number;
  level: number;
}
export interface RiskAssessment {
  dims: Record<RiskDimension, RiskDimensionResult>;
  risk: number;
  verdict: 'ok' | 'review' | 'block';
  reason: string;
}

export type JudgeTests =
  | { source: 'parsed'; allPassed: boolean; passed: number; failed: number; errors: number }
  | { source: 'judged'; allPassed: number }
  | null;

export interface DoneClaimResult {
  text: string;
  judged: number;
  accepted: boolean;
}

export interface JudgeResult {
  succeeded: number;
  errorPresent: number;
  newInfo: number;
  tests: JudgeTests;
  doneClaims: DoneClaimResult[];
}

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
  calls: number;
}
export interface StepUsage {
  generator: TokenUsage;
  jev: TokenUsage;
}
export interface StepTiming {
  generatorMs: number;
  jevMs: number;
  execMs: number;
  harnessMs: number;
  totalMs: number;
}

export type StoppedAt = 'step_start' | 'before_execute' | 'complete';
export type InterruptReason = 'signal' | 'human_abort' | 'wall_time' | 'error';

export interface StepRecord {
  step: number;
  startedAt: string;
  /** effective intent (null when the stage was not reached) */
  intent: Intent | null;
  /** Jev's raw Choice, escape option included */
  intentAnswer: IntentAnswer | null;
  contextFiles: string[];
  proposal: Proposal | null;
  risk: RiskAssessment | null;
  outcome: ActionOutcome | null;
  judge: JudgeResult | null;
  completion: number | null;
  decisions: Decision[];
  jevRequests: JevRequestRecord[];
  usage: StepUsage;
  timing: StepTiming;
  /** 0..3 entries, see §6 */
  loopSignatures: string[];
  stoppedAt?: StoppedAt;
  interruptedAt?: { stage: StageName; reason: InterruptReason };
  /** stage failure (§6), redacted */
  error?: { stage: StageName; code: string; message: string };
}

export interface RunCounters {
  blocked: number;
  reviews: number;
  declined: number;
  failed: number;
  loops: number;
  replans: number;
  reads: number;
}

export interface SerializedError {
  name: string;
  code: string;
  message: string;
  exitCode: number;
}

export type EngineMode = 'jev-on' | 'jev-off' | 'jev-only'; // jev-only: no generating LLM; a Synthesizer proposes (§JEV-ONLY.md)

export interface RunResult {
  runId: string;
  mode: EngineMode;
  stopReason: StopReason;
  steps: number;
  wallMs: number;
  usage: StepUsage;
  timing: StepTiming;
  /** per committed step: generator + Jev input+output tokens (= generatorTokensPerStep[i] + jevTokensPerStep[i]) */
  tokensPerStep: number[];
  /** per committed step: generator input+output tokens (what the "flat tokens per step" goal is about) */
  generatorTokensPerStep: number[];
  /** per committed step: Jev input+output tokens (the context stage asks one Noul per candidate file) */
  jevTokensPerStep: number[];
  /** raw, one entry per Jev HTTP request */
  jevLatencyMs: number[];
  /** Σ decisions.length over committed steps */
  jevQuestions: number;
  counters: RunCounters;
  finalPlan: Plan;
  error?: SerializedError;
  resolvedJevModel: string | null;
  jevModelDrift: { step: number; served: string } | null;
}

// ---------------------------------------------------------------------------------------
// Provider (generator)
// ---------------------------------------------------------------------------------------

export interface ToolSpec {
  name: string;
  description: string;
  /** JSON Schema object; strict on Anthropic (additionalProperties false, required listed). */
  inputSchema: JsonObject;
}
export interface ToolCall {
  name: string;
  input: Json;
  rawJson: string;
}
export type ToolChoice = 'auto' | 'required' | { name: string };

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}
export interface GenerateRequest {
  system: string;
  messages: ChatMessage[];
  maxTokens: number;
  /** null = do not send the parameter (Claude Sonnet 5 rejects non-default values). */
  temperature: number | null;
  tools?: ToolSpec[];
  toolChoice?: ToolChoice;
}
export interface GenerateResult {
  /** concatenated text blocks (streamed via onDelta) */
  text: string;
  toolCalls: ToolCall[];
  usage: TokenUsage;
  model: string;
  stopReason: string;
  latencyMs: number;
}
export interface GenerateOptions {
  signal: AbortSignal;
  onDelta?: (text: string) => void;
  /** streamed tool-call argument fragments (for the TUI's "streaming action… N chars") */
  onToolDelta?: (fragment: string) => void;
}
export type ProviderName = 'anthropic' | 'openrouter' | 'mock';
export interface Provider {
  readonly name: ProviderName;
  readonly model: string;
  generate(req: GenerateRequest, opts: GenerateOptions): Promise<GenerateResult>;
}

// ---------------------------------------------------------------------------------------
// Decider (Jev)
// ---------------------------------------------------------------------------------------

export interface AskOptions {
  signal: AbortSignal;
  stage: StageName;
  step: number;
}
export interface AskResult {
  answers: Record<string, Answer>;
  usage: TokenUsage;
  latencyMs: number;
  /** served model id as reported by the response */
  model: string;
  requestHash: string;
  attempts: number;
  /** response id / x-generation-id, for traceability */
  id: string | null;
}
export interface Decider {
  readonly model: string;
  ask(state: Json, questions: Record<string, Question>, opts: AskOptions): Promise<AskResult>;
}

// ---------------------------------------------------------------------------------------
// Confirmation
// ---------------------------------------------------------------------------------------

export interface ConfirmRequest {
  id: string;
  step: number;
  proposal: Proposal;
  risk: RiskAssessment;
}
export interface Confirmer {
  /** Resolves true (approve) or false (decline). Rejects with AbortError when `signal` aborts. Never auto-approves. */
  confirm(req: ConfirmRequest, opts: { signal: AbortSignal }): Promise<boolean>;
  /** Human-readable identity used in the declined reason ("reviewer" | "no reviewer in bench runs" | ...). */
  readonly identity: string;
}

// ---------------------------------------------------------------------------------------
// Spend
// ---------------------------------------------------------------------------------------

export type SpendSource = 'generator' | 'jev';
export interface SpendSnapshot {
  generator: TokenUsage;
  jev: TokenUsage;
  totalUsd: number;
  capUsd: number;
  exceeded: boolean;
}
export interface SpendMeter {
  /** never throws; records (and forwards to the parent) first, then evaluates */
  add(source: SpendSource, usage: TokenUsage): SpendSnapshot;
  /** totalUsd >= capUsd, or parent.exceeded() */
  exceeded(): boolean;
  snapshot(): SpendSnapshot;
  /** --resume: restores this meter only, does not re-add to the parent */
  restore(s: SpendSnapshot): void;
  /** bench: per-run meter under the shared bench meter */
  child(capUsd: number): SpendMeter;
}

// ---------------------------------------------------------------------------------------
// Workspace and sandbox
// ---------------------------------------------------------------------------------------

export interface Candidate {
  path: string;
  bytes: number;
}
export interface CandidateView extends Candidate {
  mentionsInTask: number;
  touchedThisRun: boolean;
}
export interface FileView {
  path: string;
  content: string;
  bytes: number;
  truncatedBytes: number;
}
export type TestRunner = 'pytest' | 'jest' | 'vitest' | 'npm' | 'cargo' | 'go' | 'unknown';
export interface TestCommand {
  command: string;
  runner: TestRunner;
}
export interface TestCounts {
  passed: number;
  failed: number;
  errors: number;
  skipped: number;
}
export interface WorkspaceInfo {
  root: string;
  git: boolean;
  hasTests: boolean;
  testCommand: TestCommand | null;
}
export interface TargetInfo {
  path: string;
  existsBefore: boolean;
  tracked: boolean;
  createdThisRun: boolean;
  recoverable: boolean;
}
export interface Workspace {
  /** realpath(workspace) */
  readonly root: string;
  info(): Promise<WorkspaceInfo>;
  /** cached listing (§8); binaries, > 1 MB, symlinks, secret paths dropped */
  listCandidates(): Promise<Candidate[]>;
  /** call after a `run` outcome: re-list (only new paths are stat'ed) */
  invalidateCandidates(): Promise<void>;
  /** call after edit/write/patch with the changed files */
  noteChanged(paths: string[]): Promise<void>;
  /** PathEscapeError / SecretPathError; head kept, truncatedBytes recorded */
  read(path: string, maxBytes: number): Promise<FileView>;
  /** EditError('no match' | 'N matches'); atomic write */
  applyEdit(a: Extract<Action, { kind: 'edit' }>): Promise<{ changedFiles: string[] }>;
  writeFile(a: Extract<Action, { kind: 'write' }>): Promise<{ changedFiles: string[]; created: boolean }>;
  /** git apply --check then git apply through workspace/git.ts; PatchError { hunk }; all-or-nothing */
  applyPatch(diff: string): Promise<{ changedFiles: string[] }>;
  /** pure; pytest/jest/cargo summaries, parsed from the tail */
  parseTestOutput(runner: TestRunner, output: string): TestCounts | null;
  /**
   * relative to the snapshot taken by createWorkspace() (§8). File actions are tracked directly;
   * changes made by commands are picked up by the `git status` refresh that invalidateCandidates()
   * performs after every `run`, so one status spawn serves the whole step (§12 budget).
   */
  changedFiles(): Promise<string[]>;
  target(path: string, createdThisRun: ReadonlySet<string>): Promise<TargetInfo>;
  /** files the run created (write/patch), tracked by the engine and passed back for target() */
}

export type SandboxLevel = 'seatbelt' | 'none';
export type SandboxProfile = 'auto' | 'seatbelt' | 'none';

export interface SandboxRunOptions {
  /** already clamped by the execute stage (§6, §8) */
  timeoutMs: number;
  /** default 200 KB; passing it never kills */
  maxOutputBytes: number;
  /** engine.signal; kills the tree (§8) */
  signal: AbortSignal;
  /** live tail for the transcript */
  onOutput?: (stream: 'stdout' | 'stderr', chunk: string) => void;
  /** extra env for harness-internal git (§8 defence 2); merged over the scrubbed allowlist */
  env?: Record<string, string>;
  /** override cwd (bench evaluators); must be inside the workspace or the run dir */
  cwd?: string;
  /** which kill reason to record when `signal` aborts (default 'abort') */
  abortKilledBy?: KilledBy;
}
export interface Sandbox {
  /** printed by `jevcode config` */
  readonly level: SandboxLevel;
  run(command: string, opts: SandboxRunOptions): Promise<ExecResult>;
  /** three-pass tree kill (§8); used by abort() and fatal() */
  killAll(): Promise<void>;
}

// ---------------------------------------------------------------------------------------
// Checkpoint contract (§9)
// ---------------------------------------------------------------------------------------

/** One element of state.recent (§5.5) and of the generator's window. */
export interface WindowEntry {
  step: number;
  intent: Intent | null;
  /** "edit src/a.py", "run pytest -q", "done" */
  action: string;
  outcome: OutcomeStatus | null;
  /** blocked / declined / failed reason, verbatim, <= 600 chars */
  reason?: string;
  judge?: JudgeResult;
  completion?: number;
  /** <= 600 chars: head 400 + tail 200 */
  output?: string;
  truncated?: boolean;
  /** context files plus `read` paths for that step */
  shownFiles: string[];
  notes: string[];
}

export interface LoopDetectorState {
  counts: Record<string, number>;
  lastSignature: string | null;
  tripped: boolean;
  replanCount: number;
  tripsBySignature: Record<string, { trips: number; directives: { step: number; directive: string }[] }>;
}

export interface LastTestRun {
  step: number;
  command: string;
  passed: number;
  failed: number;
  errors: number;
  allPassed: boolean;
}

export interface CheckpointState {
  runId: string;
  mode: EngineMode;
  /** number of COMMITTED steps; the next step to run is step + 1 */
  step: number;
  plan: Plan;
  /** exactly what loop/window.ts feeds the next prompt */
  window: WindowEntry[];
  loopDetector: LoopDetectorState;
  /** cumulative generator + Jev over the whole run, all resumes */
  spend: SpendSnapshot;
  /** active wall time summed across resumes; --max-wall applies to this */
  wallMsUsed: number;
  timing: StepTiming;
  jevLatencyMs: number[];
  tokensPerStep: number[];
  /** per-source split of tokensPerStep; absent in older checkpoints = zeros of tokensPerStep's length */
  generatorTokensPerStep?: number[];
  jevTokensPerStep?: number[];
  counters: RunCounters;
  /** replan directive pending for the next step */
  directive: ReplanDirective | null;
  lastTestRun: LastTestRun | null;
  lastChangeStep: number | null;
  createdThisRun: string[];
  resolvedJevModel: string | null;
  jevModelDrift: { step: number; served: string } | null;
  stopReason: StopReason | null;
  error?: { stage: StageName; code: string };
  /** §9.1 rule 1: a discarded (uncommitted) step */
  interrupted: { step: number; stage: StageName; proposal: Proposal | null } | null;
  consecutiveStageFailures: number;
  /** Σ decisions.length over committed steps (RunResult.jevQuestions); absent in older checkpoints */
  jevQuestions?: number;
  resumes: number;
  updatedAt: string;
}

export interface CheckpointEnvelope {
  version: 1;
  /** sha256 of JSON.stringify(state) */
  checksum: string;
  state: CheckpointState;
}

export interface ConfigRecordValue {
  value: string | { source: string; fingerprint: string };
  source: string;
}
export interface RunMeta {
  runId: string;
  task: string;
  workspace: string;
  mode: EngineMode;
  /** secrets as fingerprints (§3) */
  config: Record<string, ConfigRecordValue>;
  versions: { jevcode: string; node: string };
  createdAt: string;
  /** appended on resume (§9) */
  overrides: { setting: string; from: string; to: string; atStep: number }[];
  resumes: { resumedAt: string; previousStopReason: StopReason | null }[];
  resolvedJevModel: string | null;
  jevModelDrift: { step: number; served: string } | null;
}

export interface GeneratorCallRecord {
  step: number;
  attempt: number;
  promptHash: string;
  model: string;
  temperature: number | null;
  maxTokens: number;
  usage: TokenUsage;
  latencyMs: number;
  stopReason: string;
  malformed: boolean;
}

export interface CheckpointStore {
  readonly dir: string;
  create(meta: RunMeta): Promise<void>;
  /** CheckpointError, exit 3 */
  load(): Promise<{ meta: RunMeta; state: CheckpointState; recoveredFrom: 'state' | 'prev' }>;
  updateMeta(patch: Partial<Pick<RunMeta, 'overrides' | 'resumes' | 'resolvedJevModel' | 'jevModelDrift'>>): Promise<void>;
  /** write tmp + fsync; rename state.json -> state.prev.json; rename tmp -> state.json */
  writeState(state: CheckpointState): Promise<void>;
  /** synchronous last resort used by shutdown() on a second Ctrl-C or on 'exit' */
  writeStateSync(state: CheckpointState): void;
  appendStep(r: StepRecord): Promise<void>;
  appendDecisions(d: readonly Decision[]): Promise<void>;
  appendJevRequest(r: JevRequestRecord): Promise<void>;
  appendGenerator(g: GeneratorCallRecord): Promise<void>;
  appendTranscript(line: string): Promise<void>;
  /** steps.jsonl records with step > state.step (resume folds them into the window) */
  readStepsAfter(step: number): Promise<StepRecord[]>;
  /** awaited by shutdown() before exit */
  flush(): Promise<void>;
  /** non-fatal warnings (prev fallback, torn steps.jsonl lines) */
  lastWarnings?(): readonly string[];
}

// ---------------------------------------------------------------------------------------
// Engine surface
// ---------------------------------------------------------------------------------------

export interface RunLimits {
  maxSteps: number;
  maxWallMs: number;
  maxReplans: number;
  completeThreshold: number;
  impossibleThreshold: number;
  commandTimeoutMs: number;
  maxCommandTimeoutMs: number;
  maxOutputBytes: number;
  spendCapUsd: number;
}

export interface EngineOptions {
  task: string;
  mode: EngineMode;
  /** realpath is taken by createWorkspace() */
  workspace: string;
  runsDir: string;
  resume?: { runId: string; force: boolean };
  provider: Provider;
  decider: Decider;
  confirmer: Confirmer;
  meter: SpendMeter;
  limits: RunLimits;
  sandboxProfile: SandboxProfile;
  noNetwork: boolean;
  /** masked config for run.json (§3) */
  configRecord: Record<string, ConfigRecordValue>;
  /** redaction function built by resolveConfig (§8.4) */
  redact: (s: string) => string;
  /** secret file paths never read/written (§8) */
  secretPaths: readonly string[];
  /** generator sampling; temperature null = not sent */
  generation: { temperature: number | null; maxTokens: number };
  /** decider model pinning info (§5.4 rule 7) */
  deciderModel: { configured: string; pinned: boolean };
  /** extra directories the sandbox may write to (bench stand-ins for /output etc.); realpath'ed into the profile */
  extraWritableRoots?: readonly string[];
  /** extra directories the sandbox may read but not write (bench object caches) */
  extraReadableRoots?: readonly string[];
  /** jev-only mode: proposes actions with Jev + code search, no generating LLM (required when mode === 'jev-only') */
  synthesizer?: Synthesizer;
  /** injectable clock for perf/unit tests */
  now?: () => number;
  /** injected exit for tests of the forced second Ctrl-C path */
  exit?: (code: number) => never;
}

// ---------------------------------------------------------------------------------------
// Jev-only synthesis (docs/JEV-ONLY.md): code proposes, Jev decides, tests verify
// ---------------------------------------------------------------------------------------

export interface SynthesisContext {
  runId: string;
  step: number;
  task: string;
  plan: Plan;
  window: readonly WindowEntry[];
  intent: Intent;
  /** files the context stage selected (path -> content view) */
  contextFiles: readonly FileView[];
  workspace: Workspace;
  workspaceInfo: WorkspaceInfo;
  sandbox: Sandbox;
  decider: Decider;
  signal: AbortSignal;
  limits: RunLimits;
  redact: (s: string) => string;
  /** emit transcript/synth/decision events; the engine redacts and records them */
  emit: (e: EngineEvent) => void;
  /** ask Jev through the engine so usage, decisions.jsonl and the pane stay complete */
  ask: (stage: StageName, state: Json, questions: Record<string, Question>) => Promise<{ answers: Record<string, Answer>; rows: Decision[]; latencyMs: number }>;
  createdThisRun: ReadonlySet<string>;
  /** replan directive text when the loop detector tripped */
  directive: string | null;
}

export interface Synthesizer {
  readonly name: string;
  /** Produce exactly one proposal (usually a `patch` or `edit`, sometimes `run`/`read`/`done`) without any generating LLM. */
  synthesize(ctx: SynthesisContext): Promise<Proposal>;
}

export interface EngineStatus {
  step: number;
  maxSteps: number;
  wallMs: number;
  maxWallMs: number;
  stage: StageName | 'idle';
  spend: SpendSnapshot;
  stopReason: StopReason | null;
}

export type EngineEvent =
  | { type: 'synth'; step: number; phase: string; detail: string; candidates?: number; tested?: number } // jev-only synthesizer progress
  | { type: 'run:start'; runId: string; task: string; mode: EngineMode; resumedFromStep: number | null }
  | { type: 'run:ready'; runId: string; step: number; maxSteps: number; task: string; resumed: boolean }
  | { type: 'step:start'; step: number; startedAt: string }
  | { type: 'stage:start'; step: number; stage: StageName }
  | { type: 'stage:end'; step: number; stage: StageName; ms: number }
  | { type: 'decision'; decision: Decision }
  | { type: 'jev:request'; record: JevRequestRecord }
  | { type: 'intent'; step: number; intent: Intent; answer: IntentAnswer; probability: number; confidence: number }
  | { type: 'context'; step: number; files: string[]; bytes: number; candidates: number }
  | { type: 'generator:start'; step: number; attempt: number }
  | { type: 'generator:delta'; step: number; text: string }
  | { type: 'generator:tool-delta'; step: number; chars: number } // cumulative streamed tool-argument chars ("streaming action… N chars")
  | { type: 'generator:end'; step: number; usage: TokenUsage; latencyMs: number; finishReason: string }
  | { type: 'proposal'; step: number; proposal: Proposal }
  | { type: 'risk'; step: number; risk: RiskAssessment }
  | { type: 'confirm:request'; request: ConfirmRequest }
  | { type: 'confirm:resolved'; step: number; id: string; approved: boolean; aborted: boolean }
  | { type: 'exec:start'; step: number; action: Action }
  | { type: 'exec:output'; step: number; stream: 'stdout' | 'stderr'; chunk: string }
  | { type: 'outcome'; step: number; outcome: ActionOutcome }
  | { type: 'judge'; step: number; judge: JudgeResult | null; completion: number | null }
  | { type: 'plan'; step: number; plan: Plan; rejectedDone: string[]; unverifiedDone: string[] }
  | { type: 'loop:tripped'; step: number; signature: string; occurrences: number }
  | { type: 'replan'; step: number; directive: ReplanDirective }
  | { type: 'checkpoint'; step: number; ms: number }
  | { type: 'step:end'; record: StepRecord }
  | { type: 'status'; status: EngineStatus }
  | { type: 'transcript'; step: number | null; level: 'info' | 'warn' | 'error'; text: string }
  | { type: 'error'; step: number | null; error: SerializedError; fatal: boolean }
  | { type: 'run:end'; result: RunResult };

export type EngineEventType = EngineEvent['type'];

export interface EngineEmitter {
  on<T extends EngineEventType>(type: T, fn: (e: Extract<EngineEvent, { type: T }>) => void): () => void;
  onAny(fn: (e: EngineEvent) => void): () => void;
  emit(e: EngineEvent): void;
}

export interface Engine {
  readonly runId: string;
  readonly events: EngineEmitter;
  /** the run-level AbortSignal every generate/ask/sandbox run receives */
  readonly signal: AbortSignal;
  /** resolves for every StopReason including 'error'; never rejects */
  run(): Promise<RunResult>;
  /** idempotent; see §11 shutdown() */
  abort(reason: 'human_abort' | 'signal'): void;
  status(): EngineStatus;
  /** current checkpoint state for the synchronous last-resort write (§11) */
  snapshotState(): CheckpointState | null;
}

// ---------------------------------------------------------------------------------------
// Renderer (TUI or plain), wired by cli/main.tsx
// ---------------------------------------------------------------------------------------

export interface RendererOptions {
  /** task text (or "resuming <run-id>") shown in the first frame */
  task: string;
  resumeId: string | null;
  /** called on Ctrl-C (TUI) / readline SIGINT (plain) */
  onAbort: (reason: 'human_abort' | 'signal') => void;
  stdout?: NodeJS.WriteStream;
  stdin?: NodeJS.ReadStream;
  /** plain mode when stdin is not a TTY: decline after this many ms (default 0 = immediately) */
  confirmTimeoutMs?: number;
}
export interface Renderer {
  readonly confirmer: Confirmer;
  /** subscribe to engine events; may be called after the first frame */
  attach(engine: Engine): void;
  /** resolves after Ink has flushed the first frame (perf hook) */
  firstFrame(): Promise<void>;
  unmount(): Promise<void>;
}

// ---------------------------------------------------------------------------------------
// Resolved configuration (config/*; consumed by cli/main.tsx)
// ---------------------------------------------------------------------------------------

export type ConfigSource = 'flag' | 'env' | `dotenv:${string}` | `file:${string}` | 'default' | 'run.json';

export interface Resolved<T> {
  value: T;
  source: ConfigSource;
}

export interface GeneratorConfig {
  provider: 'anthropic' | 'openrouter';
  model: string;
  apiKey: string;
  baseUrl: string;
  temperature: number | null;
  maxTokens: number;
  /** USD per million tokens, used when the API returns no cost */
  pricing: { inputPerM: number; outputPerM: number; cacheReadPerM: number; cacheWritePerM: number };
}

export interface DeciderConfig {
  baseUrl: string;
  apiKey: string;
  /** configured id, verbatim */
  model: string;
  /** normalised id ends in -YYYYMMDD */
  pinned: boolean;
}

export interface ResolvedConfig {
  /** every setting with its source; secrets appear only as fingerprints in record() */
  readonly entries: ReadonlyMap<string, Resolved<string>>;
  /** validates the generator section on first call; ConfigError names setting and sources */
  generator(): GeneratorConfig;
  /** validates the decider section on first call */
  decider(): DeciderConfig;
  limits(): RunLimits;
  workspace: string;
  runsDir: string;
  openAssistPath: string | null;
  configFile: string | null;
  /** dotenv files that were actually read */
  dotenvFiles: readonly string[];
  sandbox: SandboxProfile;
  noNetwork: boolean;
  plain: boolean;
  /** secret file paths (dotenvs, config file) for the sandbox read-deny list and SecretPathError */
  secretPaths: readonly string[];
  /** redaction built from the SecretSet (§8.4) */
  redact: (s: string) => string;
  redactJson: (v: Json) => Json;
  /** masked table for run.json and `jevcode config` */
  record(): Record<string, ConfigRecordValue>;
}

// ---------------------------------------------------------------------------------------
// Bench records (bench/*)
// ---------------------------------------------------------------------------------------

export type BenchSuite = 'swebench' | 'terminal-bench' | 'quixbugs' | 'ladder'; // quixbugs/ladder: the jev-only difficulty ladder (docs/JEV-ONLY.md)
export type BenchEvaluator = 'local-venv' | 'invalid' | 'local' | 'mock' | 'none';
export type BenchStopReason = StopReason | 'not_run';

export interface BenchTaskRecord {
  suite: BenchSuite;
  task: string;
  condition: EngineMode;
  pass: boolean | null;
  evaluator: BenchEvaluator;
  reason?: string;
  steps: number;
  wallMs: number;
  /** combined generator + Jev tokens per committed step */
  tokensPerStep: number[];
  generatorTokensPerStep: number[];
  jevTokensPerStep: number[];
  cost: { generator: number; jev: number };
  jevLatencyMs: { raw: number[]; p50: number | null; p95: number | null };
  jevRequests: number;
  jevQuestions: number;
  timing: { generatorMs: number; jevMs: number; execMs: number; harnessMs: number };
  stopReason: BenchStopReason;
  blocked: number;
  reviews: number;
  declined: number;
  loops: number;
  replans: number;
  reads: number;
  modelDrift: boolean;
  pairComplete: boolean;
  patchEmpty: boolean | null;
  patchApplied: boolean | null;
  patchBytes: number | null;
  runId: string | null;
  capFired: 'bench' | 'task' | null;
  /** official report.json shape (SWE-bench) */
  testsStatus?: { FAIL_TO_PASS: { success: string[]; failure: string[] }; PASS_TO_PASS: { success: string[]; failure: string[] } };
  evalExitCode?: number | null;
}

// ---------------------------------------------------------------------------------------
// Mock factories (provider/mock.ts, jev/mock.ts) — used by unit tests, perf and the bench
// ---------------------------------------------------------------------------------------

export interface MockTurn {
  /** streamed as text deltas */
  text?: string;
  /** returned as a tool call (the engine prefers this over fenced JSON in `text`) */
  toolCall?: ToolCall;
  usage?: Partial<TokenUsage>;
  latencyMs?: number;
  /** throw a ProviderHttpError with this status instead of answering */
  error?: { status: number; retryable: boolean };
}
export interface MockProviderOptions {
  turns: MockTurn[] | ((req: GenerateRequest, index: number) => MockTurn);
  /** deltas per second when latencyMs > 0 (default 0 = single delta) */
  deltaChunkSize?: number;
  model?: string;
}
export interface MockDeciderContext {
  stage: StageName;
  step: number;
  state: Json;
  questions: Record<string, Question>;
}
/** Return answers for some or all questions; unanswered ids fall through to the default heuristics. */
export type MockDeciderRule = (ctx: MockDeciderContext) => Partial<Record<string, Answer>> | undefined;
export interface MockDeciderOptions {
  rules?: MockDeciderRule[];
  latencyMs?: number;
  model?: string;
  /** throw JevHttpError(status) for calls matching stage/step (every attempt) */
  failAt?: { stage: StageName; step?: number; status: number; times?: number }[];
  /** return a malformed body once at this stage/step (validation path) */
  malformedAt?: { stage: StageName; step?: number; transient: boolean }[];
}

// ---------------------------------------------------------------------------------------
// Factory signatures each module must export (documentation of the wiring surface)
// ---------------------------------------------------------------------------------------
// config/resolve.ts      export function resolveConfig(flags: ParsedFlags, env: NodeJS.ProcessEnv, cwd: string): Promise<ResolvedConfig>
// jev/client.ts          export function createJevDecider(cfg: DeciderConfig, deps: { fetch?: typeof fetch; redact: (s: string) => string; referer?: string }): Decider
// jev/mock.ts            export function createMockDecider(opts?: MockDeciderOptions): Decider
// provider/anthropic.ts  export function createAnthropicProvider(cfg: GeneratorConfig, deps: { fetch?: typeof fetch; redact }): Provider
// provider/openrouter.ts export function createOpenRouterProvider(cfg: GeneratorConfig, deps: { fetch?: typeof fetch; redact }): Provider
// provider/mock.ts       export function createMockProvider(opts: MockProviderOptions): Provider
// provider/null.ts       export function createNullProvider(): Provider   // throws ProviderError if generate() is ever called (jev-only)
// spend/meter.ts         export function createSpendMeter(capUsd: number, parent?: SpendMeter): SpendMeter
// workspace/files.ts     export function createWorkspace(root: string, runDir: string, deps: { sandbox: Sandbox; secretPaths: readonly string[]; redact }): Promise<Workspace>
// sandbox/run.ts         export function createSandbox(opts: { workspaceRoot: string; runDir: string; profile: SandboxProfile; noNetwork: boolean; secretReadDenies: readonly string[]; redact }): Sandbox
// checkpoint/store.ts    export function createCheckpointStore(runsDir: string, runId: string, redact): CheckpointStore
// checkpoint/run-id.ts   export function newRunId(now: Date, random?: () => Buffer): string; export function isValidRunId(id: string): boolean
// loop/engine.ts         export function createEngine(opts: EngineOptions): Promise<Engine>
// loop/generator-only.ts export function createGeneratorOnlyEngine(opts: EngineOptions): Promise<Engine>
// tui/App.tsx            export function createTuiRenderer(opts: RendererOptions): Renderer
// tui/plain.ts           export function createPlainRenderer(opts: RendererOptions): Renderer
// bench/conditions.ts    export const alwaysDecline: Confirmer

// ---------------------------------------------------------------------------------------
// Sandbox factory options and bench dependency injection (added 2026-09-19 for wave-1 decoupling)
// ---------------------------------------------------------------------------------------

export interface SandboxCreateOptions {
  workspaceRoot: string;
  runDir: string;
  profile: SandboxProfile;
  noNetwork: boolean;
  /** absolute paths the seatbelt profile denies reading (dotenvs, config file, ~/.ssh, ...) */
  secretReadDenies: readonly string[];
  redact: (s: string) => string;
  /** additional writable roots beyond the workspace and run dir */
  extraWritable?: readonly string[];
  /** additional read-only roots (e.g. a shared git object cache the workspace's --shared clone points at) */
  extraReadable?: readonly string[];
  /**
   * deny writes to <workspace>/.git/config and .git/hooks (default true: the agent must not plant
   * git-executed code). Bench infrastructure sandboxes that themselves `git clone` into the root pass false.
   */
  protectGit?: boolean;
}

/** Everything the bench runner needs, injected so bench/* compiles and tests without the real modules. */
export interface BenchDeps {
  createEngine(opts: EngineOptions): Promise<Engine>;
  createGeneratorOnlyEngine(opts: EngineOptions): Promise<Engine>;
  createMockProvider(opts: MockProviderOptions): Provider;
  createMockDecider(opts?: MockDeciderOptions): Decider;
  createSpendMeter(capUsd: number, parent?: SpendMeter): SpendMeter;
  createSandbox(opts: SandboxCreateOptions): Sandbox;
  /** present only with --live */
  liveProvider?: Provider;
  liveDecider?: Decider;
}
