/**
 * JevCode shared contract (DESIGN.md §4, frozen for parallel implementation).
 *
 * Every module imports from here and from ../errors.ts. Implementers do not edit this file;
 * needed changes are reported back and reconciled centrally. Function declarations at the
 * bottom name the factory each module must export, so wiring code (cli/main.tsx) and the
 * bench can be written against this file alone.
 */
// contract 1.1 (2026-09-20): additive TUI/session extensions per docs/TUI-DESIGN.md §15; every new field on an existing type is optional; CheckpointEnvelope.version stays 1.

export type Json = string | number | boolean | null | Json[] | { [k: string]: Json };
export type JsonObject = { [k: string]: Json };

// ---------------------------------------------------------------------------------------
// Generator actions (the only thing the generator produces)
// ---------------------------------------------------------------------------------------

export type Action =
  | { kind: 'read'; paths: string[] } // show files, bounded
  | { kind: 'edit'; path: string; old: string; new: string } // exact, unique match
  | { kind: 'write'; path: string; content: string } // create or overwrite
  | { kind: 'patch'; diff: string } // unified diff, -p1, applied with git apply
  | { kind: 'run'; command: string; timeoutMs?: number } // sh -c in sandbox
  | { kind: 'done'; summary: string }; // proposal to finish

export type ActionKind = Action['kind'];

export interface PlanDraft {
  done: string[];
  remaining: string[];
  openProblems: string[];
}

export interface Proposal {
  goal: string;
  action: Action;
  plan: PlanDraft;
  /** Full assistant text (streamed text plus, for tool calls, the raw JSON input). Redacted. */
  rawText: string;
  /**
   * Code-computed verification evidence attached by the jev-only synthesizer (never by a
   * generator): the proposed patch was already run against the tests in a shadow copy. The
   * risk and judge stages put it in the Jev state as `proposal.evidence` so the Scores judge
   * a verified change rather than an unverified claim (docs/JEV-ONLY-DESIGN.md §5.1).
   */
  evidence?: ProposalEvidence;
}

export interface ProposalEvidence {
  kind: 'shadow_test_run';
  /** the command the synthesizer ran in the shadow copy */
  command: string;
  before: { passed: number; failed: number; errors: number; total: number };
  after: { passed: number; failed: number; errors: number; total: number };
  /** test ids that pass after the patch and failed before (bounded to 20) */
  newlyPassing: string[];
  /** test ids that fail after the patch and passed before (must be empty for a committed candidate) */
  newlyFailing: string[];
  /** which failing tests this sub-goal targets */
  goalTests: string[];
  /** 'sieve' = every candidate at the site was run; 'rank' = Jev-ranked top-k were run */
  selection: 'sieve' | 'rank';
  /** number of candidates run for this decision, code-computed */
  candidatesTested: number;
  /** true when several candidates passed and Jev's arbitration picked this one */
  arbitrated: boolean;
}

// ---------------------------------------------------------------------------------------
// Persistent plan
// ---------------------------------------------------------------------------------------

export interface PlanItemDone {
  text: string;
  /** judged -1 = not judged (jev-off). */
  evidence: { step: number; judged: number };
}
export interface PlanUnverified {
  text: string;
  step: number;
  judged: number;
}
/** TUI-DESIGN §15 item 2: 'human' = a steer (step > 0) or a seed / undo note (step 0) */
export type HarnessProblemKind = 'replan' | 'rejected_claim' | 'stale_plan' | 'human';
export interface HarnessProblem {
  kind: HarnessProblemKind;
  text: string;
  step: number;
}
export interface Plan {
  done: PlanItemDone[];
  remaining: string[];
  /** claimed, done_<j> in [0.3, 0.7), still in remaining */
  unverified: PlanUnverified[];
  /** generator entries, replaced each step */
  openProblems: string[];
  /** harness-owned (§6 Plan) */
  harnessProblems: HarnessProblem[];
}
/** TUI-DESIGN §15 item 3: bounded plan snapshot written at commit for /rewind (each list <= 20 x 200 chars) */
export interface PlanSnapshot {
  done: PlanItemDone[];
  remaining: string[];
  unverified: PlanUnverified[];
  harnessProblems: HarnessProblem[];
}

// ---------------------------------------------------------------------------------------
// Execution
// ---------------------------------------------------------------------------------------

export type KilledBy = 'timeout' | 'wall_time' | 'abort' | null;

export interface ExecResult {
  /** exitCode === 0 && killedBy === null */
  ok: boolean;
  exitCode: number | null;
  signal: string | null;
  /** head (<= maxOutputBytes) + rolling tail (16 KB); see §8 */
  stdout: string;
  stderr: string;
  /** output cap passed; never a kill, never an error */
  truncated: boolean;
  bytesSeen: number;
  /** set by the code path that kills, before signalling */
  killedBy: KilledBy;
  /** derived: killedBy === 'timeout' */
  timedOut: boolean;
  /** pids from the kill snapshot still alive after SIGKILL (§8) */
  orphans: number[];
  /** sandbox-exec itself failed to exec the binary (exit 71) */
  sandboxExecDenied: boolean;
  durationMs: number;
}

export type ActionOutcome =
  | { status: 'executed'; exec?: ExecResult; summary: string; changedFiles: string[] }
  | { status: 'noop'; summary: string } // `done` proposal that passed risk
  | { status: 'blocked'; reason: string }
  | { status: 'declined'; reason: string } // confirmer returned false at review
  | { status: 'failed'; error: string } // patch did not apply, path escape, stage failure
  | { status: 'interrupted'; exec?: ExecResult }; // harness cancelled execute

export type OutcomeStatus = ActionOutcome['status'];

// ---------------------------------------------------------------------------------------
// Jev wire types
// ---------------------------------------------------------------------------------------

export interface NoulCriteria {
  true: Json;
  false: Json;
}
export type Question =
  | { type: 'noul'; instructions: Json; criteria?: NoulCriteria } // criteria omitted only for context Nouls (§5.5)
  | { type: 'choice'; instructions: Json; criteria: Record<string, Json | null> }
  | { type: 'score'; instructions: Json; criteria: Json[] };
export type QuestionType = Question['type'];

export type Answer =
  | { type: 'noul'; noul: number }
  | { type: 'choice'; choice: string; probabilities: Record<string, number>; confidence: number }
  | { type: 'score'; score: number; legend: Record<string, Json>; probabilities: Record<string, number>; confidence: number };

export interface JevRequest {
  model: string;
  state: Json;
  questions: Record<string, Question>;
}
export interface JevUsage {
  input_tokens: number;
  output_tokens: number;
  cost: number;
}
export interface JevResponse {
  model: string;
  answers: Record<string, Answer>;
  usage: JevUsage;
  id?: string;
  provider?: string;
}

export type StageName = 'replan' | 'intent' | 'context' | 'propose' | 'risk' | 'execute' | 'judge' | 'complete';

export type DecisionVerdict = 'ok' | 'review' | 'block' | 'chosen' | 'overridden' | 'fallback';

/** One row in the decisions pane and decisions.jsonl. */
export interface Decision {
  step: number;
  stage: StageName;
  id: string;
  question: Question;
  answer: Answer;
  /** P(chosen): noul p, choice probabilities[choice], score p_{k*} */
  probability: number;
  /** harness-computed (§5.3); for Nouls the derived |2p − 1| */
  confidence: number;
  /** risk: ok/review/block; intent, replan: chosen/overridden/fallback */
  verdict?: DecisionVerdict;
  /** the parent request's latency; display only */
  latencyMs: number;
  requestHash: string;
  /** only when it differs from the configured id (§5.4 rule 7) */
  servedModel?: string;
}

/** One per Decider.ask() call (jev.jsonl); the metric source for Jev latency. */
export interface JevRequestRecord {
  step: number;
  stage: StageName;
  requestHash: string;
  latencyMs: number;
  questions: number;
  usage: TokenUsage;
  model: string;
  attempts: number;
}

// ---------------------------------------------------------------------------------------
// Loop
// ---------------------------------------------------------------------------------------

/** What the generator sees (effective intent). */
export type Intent = 'investigate' | 'edit' | 'verify' | 'fix_environment' | 'finish';
/** What Jev may answer. */
export type IntentAnswer = Intent | 'none_of_these';

export type StopReason =
  | 'complete'
  | 'max_steps'
  | 'spend_cap'
  | 'wall_time'
  | 'max_replans'
  | 'human_abort'
  | 'signal'
  | 'replan_stop'
  | 'impossible'
  | 'generator_done' // Jev-off only
  | 'error'
  | 'human_pause' // TUI-DESIGN §15 item 1: Esc / pause at the loop top; exit-4 family, resumable without --force
  | 'token_cap'; // TUI-DESIGN §15 item 1: RunLimits.maxGeneratorTokens reached (allowUnpriced); a plain budget stop
/** TUI-DESIGN §15 item 1: the signal behind abort('signal'); exitCodeFor maps to 130 / 143 / 129 */
export type SignalName = 'SIGINT' | 'SIGTERM' | 'SIGHUP';

export type ReplanMove = 'change_approach' | 'gather_context' | 'fix_environment' | 'revert_changes' | 'stop_and_report' | 'none_of_these';

export interface ReplanDirective {
  move: ReplanMove;
  probability: number;
  confidence: number;
  taskImpossible: number;
  text: string;
}

export type RiskDimension = 'destructive' | 'out_of_scope' | 'plan_mismatch' | 'irreversible';
export const RISK_DIMENSIONS: readonly RiskDimension[] = ['destructive', 'out_of_scope', 'plan_mismatch', 'irreversible'];

export interface RiskDimensionResult {
  risk: number;
  /** P(argmax level) */
  probability: number;
  expected: number;
  tailMass: number;
  bound: 'expected' | 'tail';
  confidence: number;
  level: number;
}
export interface RiskAssessment {
  dims: Record<RiskDimension, RiskDimensionResult>;
  risk: number;
  verdict: 'ok' | 'review' | 'block';
  reason: string;
}

export type JudgeTests =
  | { source: 'parsed'; allPassed: boolean; passed: number; failed: number; errors: number }
  | { source: 'judged'; allPassed: number }
  | null;

export interface DoneClaimResult {
  text: string;
  judged: number;
  accepted: boolean;
}

export interface JudgeResult {
  succeeded: number;
  errorPresent: number;
  newInfo: number;
  tests: JudgeTests;
  doneClaims: DoneClaimResult[];
}

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
  calls: number;
}
export interface StepUsage {
  generator: TokenUsage;
  jev: TokenUsage;
}
export interface StepTiming {
  generatorMs: number;
  jevMs: number;
  execMs: number;
  harnessMs: number;
  totalMs: number;
  /** TUI-DESIGN §15 item 3: pre + post images (§12.3); already inside harnessMs, reported separately */
  imagesMs?: number;
}

export type StoppedAt = 'step_start' | 'before_execute' | 'complete';
export type InterruptReason = 'signal' | 'human_abort' | 'wall_time' | 'error';

export interface StepRecord {
  step: number;
  startedAt: string;
  /** effective intent (null when the stage was not reached) */
  intent: Intent | null;
  /** Jev's raw Choice, escape option included */
  intentAnswer: IntentAnswer | null;
  contextFiles: string[];
  proposal: Proposal | null;
  risk: RiskAssessment | null;
  outcome: ActionOutcome | null;
  judge: JudgeResult | null;
  completion: number | null;
  decisions: Decision[];
  jevRequests: JevRequestRecord[];
  usage: StepUsage;
  timing: StepTiming;
  /** 0..3 entries, see §6 */
  loopSignatures: string[];
  stoppedAt?: StoppedAt;
  interruptedAt?: { stage: StageName; reason: InterruptReason };
  /** stage failure (§6), redacted */
  error?: { stage: StageName; code: string; message: string };
  /** TUI-DESIGN §15 item 3: the committed plan after this step, bounded, for /rewind */
  planAfter?: PlanSnapshot;
}

export interface RunCounters {
  blocked: number;
  reviews: number;
  declined: number;
  failed: number;
  loops: number;
  replans: number;
  reads: number;
}

export interface SerializedError {
  name: string;
  code: string;
  message: string;
  exitCode: number;
  /** TUI-DESIGN §15 item 4: HTTP status when the error was an HTTP failure */
  status?: number;
  /** TUI-DESIGN §15 item 4 */
  retryable?: boolean;
  /** TUI-DESIGN §15 item 4 */
  side?: 'jev' | 'generator';
  /** TUI-DESIGN §15 item 4: response id / x-generation-id when known */
  requestId?: string | null;
}

export type EngineMode = 'jev-on' | 'jev-off' | 'jev-only'; // jev-only: no generating LLM; a Synthesizer proposes (§JEV-ONLY.md)

export interface RunResult {
  runId: string;
  mode: EngineMode;
  stopReason: StopReason;
  steps: number;
  wallMs: number;
  usage: StepUsage;
  timing: StepTiming;
  /** per committed step: generator + Jev input+output tokens (= generatorTokensPerStep[i] + jevTokensPerStep[i]) */
  tokensPerStep: number[];
  /** per committed step: generator input+output tokens (what the "flat tokens per step" goal is about) */
  generatorTokensPerStep: number[];
  /** per committed step: Jev input+output tokens (the context stage asks one Noul per candidate file) */
  jevTokensPerStep: number[];
  /** raw, one entry per Jev HTTP request */
  jevLatencyMs: number[];
  /** Σ decisions.length over committed steps */
  jevQuestions: number;
  counters: RunCounters;
  finalPlan: Plan;
  error?: SerializedError;
  resolvedJevModel: string | null;
  jevModelDrift: { step: number; served: string } | null;
}

// ---------------------------------------------------------------------------------------
// Provider (generator)
// ---------------------------------------------------------------------------------------

export interface ToolSpec {
  name: string;
  description: string;
  /** JSON Schema object; strict on Anthropic (additionalProperties false, required listed). */
  inputSchema: JsonObject;
}
export interface ToolCall {
  name: string;
  input: Json;
  rawJson: string;
}
export type ToolChoice = 'auto' | 'required' | { name: string };

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}
export interface GenerateRequest {
  system: string;
  messages: ChatMessage[];
  maxTokens: number;
  /** null = do not send the parameter (Claude Sonnet 5 rejects non-default values). */
  temperature: number | null;
  tools?: ToolSpec[];
  toolChoice?: ToolChoice;
}
export interface GenerateResult {
  /** concatenated text blocks (streamed via onDelta) */
  text: string;
  toolCalls: ToolCall[];
  usage: TokenUsage;
  model: string;
  stopReason: string;
  latencyMs: number;
}
/** TUI-DESIGN §15 item 5: why a client is about to sleep before a retry; message = redacted <= 200-char hint, never a body */
export interface RetryCause {
  kind: 'http' | 'network' | 'timeout' | 'invalid' | 'stream';
  status: number | null;
  code: string | null;
  message: string;
}
/** TUI-DESIGN §15 item 5 */
export interface RetryInfo {
  attempt: number;
  maxAttempts: number;
  waitMs: number;
  retryAfter: boolean;
  cause: RetryCause;
}
export interface GenerateOptions {
  signal: AbortSignal;
  onDelta?: (text: string) => void;
  /** streamed tool-call argument fragments (for the TUI's "streaming action… N chars") */
  onToolDelta?: (fragment: string) => void;
  /** TUI-DESIGN §15 item 5: called before each retry sleep */
  onRetry?: (info: RetryInfo) => void;
  /** TUI-DESIGN §15 item 5: a GETTER read before each sleep (one AbortController per sleep); clients: `await sleep(waitMs, signal, opts.wake?.())` */
  wake?: () => AbortSignal | undefined;
}
export type ProviderName = 'anthropic' | 'openrouter' | 'mock';
export interface Provider {
  readonly name: ProviderName;
  readonly model: string;
  generate(req: GenerateRequest, opts: GenerateOptions): Promise<GenerateResult>;
}

// ---------------------------------------------------------------------------------------
// Decider (Jev)
// ---------------------------------------------------------------------------------------

export interface AskOptions {
  signal: AbortSignal;
  stage: StageName;
  step: number;
  /** TUI-DESIGN §15 item 5 */
  onRetry?: (info: RetryInfo) => void;
  /** TUI-DESIGN §15 item 5 */
  wake?: () => AbortSignal | undefined;
}
export interface AskResult {
  answers: Record<string, Answer>;
  usage: TokenUsage;
  latencyMs: number;
  /** served model id as reported by the response */
  model: string;
  requestHash: string;
  attempts: number;
  /** response id / x-generation-id, for traceability */
  id: string | null;
}
export interface Decider {
  readonly model: string;
  ask(state: Json, questions: Record<string, Question>, opts: AskOptions): Promise<AskResult>;
}

// ---------------------------------------------------------------------------------------
// Confirmation
// ---------------------------------------------------------------------------------------

export interface ConfirmRequest {
  id: string;
  step: number;
  proposal: Proposal;
  risk: RiskAssessment;
  /** TUI-DESIGN §15 item 6: draft.matchesIntent -> row 8 of reviewHeaderLines (§6.1); spread in only when not null */
  matchesIntent?: number | null;
  /** TUI-DESIGN §15 item 6: the risk stage's Jev latency for the 120-column title */
  jevLatencyMs?: number;
}
/** TUI-DESIGN §15 item 6: note = redacted, <= 600, one line; `...(note ? { note } : {})` */
export interface ConfirmOutcome {
  approved: boolean;
  note?: string;
}
export interface Confirmer {
  /** Resolves true (approve) or false (decline). Rejects with AbortError when `signal` aborts. Never auto-approves. */
  confirm(req: ConfirmRequest, opts: { signal: AbortSignal }): Promise<boolean>;
  /** TUI-DESIGN §15 item 6: preferred by the engine when present; the TUI implements it for the `d` note */
  confirmDetailed?(req: ConfirmRequest, opts: { signal: AbortSignal }): Promise<ConfirmOutcome>;
  /** Human-readable identity used in the declined reason ("reviewer" | "no reviewer in bench runs" | ...). */
  readonly identity: string;
}

// ---------------------------------------------------------------------------------------
// Spend
// ---------------------------------------------------------------------------------------

export type SpendSource = 'generator' | 'jev';
export interface SpendSnapshot {
  generator: TokenUsage;
  jev: TokenUsage;
  totalUsd: number;
  capUsd: number;
  exceeded: boolean;
  /** TUI-DESIGN §15 item 7: the parent (session) meter's exceeded(); present only with a parent (conditional spread) */
  parentExceeded?: boolean;
  /** TUI-DESIGN §15 item 7: the parent's totals; present only with a parent */
  parent?: { totalUsd: number; capUsd: number };
}
export interface SpendMeter {
  /** never throws; records (and forwards to the parent) first, then evaluates */
  add(source: SpendSource, usage: TokenUsage): SpendSnapshot;
  /** totalUsd >= capUsd, or parent.exceeded() */
  exceeded(): boolean;
  snapshot(): SpendSnapshot;
  /** --resume: restores this meter only, does not re-add to the parent */
  restore(s: SpendSnapshot): void;
  /** bench: per-run meter under the shared bench meter */
  child(capUsd: number): SpendMeter;
  /** TUI-DESIGN §15 item 7: root meter: replace the cap (USD or +Infinity); children keep forwarding to the same object; never recreate a meter */
  setCap?(capUsd: number): void;
}

// ---------------------------------------------------------------------------------------
// Workspace and sandbox
// ---------------------------------------------------------------------------------------

export interface Candidate {
  path: string;
  bytes: number;
}
export interface CandidateView extends Candidate {
  mentionsInTask: number;
  touchedThisRun: boolean;
}
export interface FileView {
  path: string;
  content: string;
  bytes: number;
  truncatedBytes: number;
}
export type TestRunner = 'pytest' | 'django' | 'sympy_bintest' | 'unittest' | 'jest' | 'vitest' | 'npm' | 'cargo' | 'go' | 'unknown';
export interface TestCommand {
  command: string;
  runner: TestRunner;
  /**
   * The command for a subset of the suite (test file paths, node ids or runner labels), built
   * per runner by workspace/tests.ts: pytest appends paths / node ids, Django's runtests.py takes
   * dotted labels, sympy's bin/test takes paths (+ `-k` names), unittest takes module names.
   * Absent when the runner cannot scope. A function: JSON serialisation drops it, so states and
   * checkpoints carry `command` and `runner` only.
   */
  scope?: (targets: readonly string[]) => string;
}
export interface TestCounts {
  passed: number;
  failed: number;
  errors: number;
  skipped: number;
}
export interface WorkspaceInfo {
  root: string;
  git: boolean;
  hasTests: boolean;
  testCommand: TestCommand | null;
  /** TUI-DESIGN §15 item 12: the run-start probe (§12.1) when one was handed to createWorkspace */
  gitState?: GitState;
}

// TUI-DESIGN §15 item 12: git facts probed once at run start (workspace/gitstate.ts, two unsandboxed spawns)
export interface StatusEntryV2 {
  xy: string;
  sub: string;
  path: string;
  from?: string;
  hH?: string;
  hI?: string;
  mode?: string;
}
export type GitHead = { kind: 'branch'; name: string; oid: string | null } | { kind: 'detached'; oid: string } | { kind: 'unborn'; name: string };
export interface GitState {
  repo: boolean;
  reason?: 'not-a-repo' | 'git-missing' | 'bare' | 'timeout';
  gitDir: string | null;
  commonDir: string | null;
  topLevel: string | null;
  prefix: string;
  linkedWorktree: boolean;
  head: GitHead | null;
  upstream: string | null;
  ahead: number | null;
  behind: number | null;
  dirty: { modified: number; staged: number; untracked: number; renamed: number; unmerged: number; submodules: number; entries: StatusEntryV2[] };
  probedAt: string;
  probeMs: number;
}
/** TUI-DESIGN §15 item 12: what run.json keeps of the probe; `end` from the run:end re-probe (P51), `resumedOn` on --resume when head moved (P52) */
export type RunGitMeta = Pick<GitState, 'repo' | 'reason' | 'head' | 'upstream' | 'linkedWorktree' | 'prefix'> & {
  dirtyAtStart: { modified: number; staged: number; untracked: number };
  end?: Pick<GitState, 'head' | 'upstream' | 'ahead' | 'behind'> & { dirty: { modified: number; staged: number; untracked: number } };
  resumedOn?: GitHead | null;
};
export interface TargetInfo {
  path: string;
  existsBefore: boolean;
  tracked: boolean;
  createdThisRun: boolean;
  recoverable: boolean;
}
export interface Workspace {
  /** realpath(workspace) */
  readonly root: string;
  info(): Promise<WorkspaceInfo>;
  /** cached listing (§8); binaries, > 1 MB, symlinks, secret paths dropped */
  listCandidates(): Promise<Candidate[]>;
  /** call after a `run` outcome: re-list (only new paths are stat'ed) */
  invalidateCandidates(): Promise<void>;
  /** call after edit/write/patch with the changed files */
  noteChanged(paths: string[]): Promise<void>;
  /** PathEscapeError / SecretPathError; head kept, truncatedBytes recorded */
  read(path: string, maxBytes: number): Promise<FileView>;
  /** EditError('no match' | 'N matches'); atomic write */
  applyEdit(a: Extract<Action, { kind: 'edit' }>): Promise<{ changedFiles: string[] }>;
  writeFile(a: Extract<Action, { kind: 'write' }>): Promise<{ changedFiles: string[]; created: boolean }>;
  /** git apply --check then git apply through workspace/git.ts; PatchError { hunk }; all-or-nothing */
  applyPatch(diff: string): Promise<{ changedFiles: string[] }>;
  /** pure; pytest/jest/cargo summaries, parsed from the tail */
  parseTestOutput(runner: TestRunner, output: string): TestCounts | null;
  /**
   * relative to the snapshot taken by createWorkspace() (§8). File actions are tracked directly;
   * changes made by commands are picked up by the `git status` refresh that invalidateCandidates()
   * performs after every `run`, so one status spawn serves the whole step (§12 budget).
   */
  changedFiles(): Promise<string[]>;
  target(path: string, createdThisRun: ReadonlySet<string>): Promise<TargetInfo>;
  /** files the run created (write/patch), tracked by the engine and passed back for target() */
  /** TUI-DESIGN §15 item 8: mention-only read of a secret path behind --allow-secret-mention (§10.4) */
  readSecretForMention?(rel: string, maxBytes: number): Promise<FileView>;
  /** TUI-DESIGN §15 item 8: the run-start probe handed in by createEngine (§12.1), refreshed by invalidateCandidates() */
  gitState?(): GitState | null;
  /** TUI-DESIGN §15 item 8: snapshotDirty ∪ statusEntries ∪ touched, in memory */
  dirtySet?(): ReadonlySet<string>;
}

export type SandboxLevel = 'seatbelt' | 'none';
export type SandboxProfile = 'auto' | 'seatbelt' | 'none';

export interface SandboxRunOptions {
  /** already clamped by the execute stage (§6, §8) */
  timeoutMs: number;
  /** default 200 KB; passing it never kills */
  maxOutputBytes: number;
  /** engine.signal; kills the tree (§8) */
  signal: AbortSignal;
  /** live tail for the transcript */
  onOutput?: (stream: 'stdout' | 'stderr', chunk: string) => void;
  /** extra env for harness-internal git (§8 defence 2); merged over the scrubbed allowlist */
  env?: Record<string, string>;
  /** override cwd (bench evaluators); must be inside the workspace or the run dir */
  cwd?: string;
  /** which kill reason to record when `signal` aborts (default 'abort') */
  abortKilledBy?: KilledBy;
}
export interface Sandbox {
  /** printed by `jevcode config` */
  readonly level: SandboxLevel;
  run(command: string, opts: SandboxRunOptions): Promise<ExecResult>;
  /** three-pass tree kill (§8); used by abort() and fatal() */
  killAll(): Promise<void>;
}

// ---------------------------------------------------------------------------------------
// Checkpoint contract (§9)
// ---------------------------------------------------------------------------------------

/** One element of state.recent (§5.5) and of the generator's window. */
export interface WindowEntry {
  step: number;
  intent: Intent | null;
  /** "edit src/a.py", "run pytest -q", "done" */
  action: string;
  outcome: OutcomeStatus | null;
  /** blocked / declined / failed reason, verbatim, <= 600 chars */
  reason?: string;
  judge?: JudgeResult;
  completion?: number;
  /** <= 600 chars: head 400 + tail 200 */
  output?: string;
  truncated?: boolean;
  /** context files plus `read` paths for that step */
  shownFiles: string[];
  notes: string[];
}

export interface LoopDetectorState {
  counts: Record<string, number>;
  lastSignature: string | null;
  tripped: boolean;
  replanCount: number;
  tripsBySignature: Record<string, { trips: number; directives: { step: number; directive: string }[] }>;
}

export interface LastTestRun {
  step: number;
  command: string;
  passed: number;
  failed: number;
  errors: number;
  allPassed: boolean;
}

export interface CheckpointState {
  runId: string;
  mode: EngineMode;
  /** number of COMMITTED steps; the next step to run is step + 1 */
  step: number;
  plan: Plan;
  /** exactly what loop/window.ts feeds the next prompt */
  window: WindowEntry[];
  loopDetector: LoopDetectorState;
  /** cumulative generator + Jev over the whole run, all resumes */
  spend: SpendSnapshot;
  /** active wall time summed across resumes; --max-wall applies to this */
  wallMsUsed: number;
  timing: StepTiming;
  jevLatencyMs: number[];
  tokensPerStep: number[];
  /** per-source split of tokensPerStep; absent in older checkpoints = zeros of tokensPerStep's length */
  generatorTokensPerStep?: number[];
  jevTokensPerStep?: number[];
  counters: RunCounters;
  /** replan directive pending for the next step */
  directive: ReplanDirective | null;
  lastTestRun: LastTestRun | null;
  lastChangeStep: number | null;
  createdThisRun: string[];
  resolvedJevModel: string | null;
  jevModelDrift: { step: number; served: string } | null;
  stopReason: StopReason | null;
  error?: { stage: StageName; code: string };
  /** §9.1 rule 1: a discarded (uncommitted) step */
  interrupted: { step: number; stage: StageName; proposal: Proposal | null } | null;
  consecutiveStageFailures: number;
  /** Σ decisions.length over committed steps (RunResult.jevQuestions); absent in older checkpoints */
  jevQuestions?: number;
  /** opaque jev-only synthesizer state (docs/JEV-ONLY-DESIGN.md §5.2); absent for other modes */
  synthState?: Json;
  /** TUI-DESIGN §15 item 9: <= 8 steers queued and not yet applied (activeHuman is re-derived from plan.harnessProblems on resume, not stored) */
  pendingDirectives?: PendingDirective[];
  /** TUI-DESIGN §15 item 9: <= 20; carried from the seed or EngineOptions.undoLog, never written into a finished run */
  undoLog?: UndoLogEntry[];
  /** TUI-DESIGN §15 item 9 */
  checkpointDegraded?: boolean;
  resumes: number;
  updatedAt: string;
}

/** TUI-DESIGN §15 item 9: a queued steer; raw in memory (§8.6), masked on disk by the store's write-time redaction (P56) */
export interface PendingDirective {
  text: string;
  at: string;
  index: number;
}
/** TUI-DESIGN §15 item 9 */
export type UndoSkipReason = 'link' | 'escape' | 'submodule' | 'not-recoverable' | 'head-moved' | 'refused' | 'declined' | 'cap' | 'size';
/** TUI-DESIGN §15 item 9 */
export interface UndoLogEntry {
  runId: string;
  step: number;
  at: string;
  by: 'undo' | 'rewind';
  restored: string[];
  skipped: { path: string; reason: UndoSkipReason }[];
}

export interface CheckpointEnvelope {
  version: 1;
  /** sha256 of JSON.stringify(state) */
  checksum: string;
  state: CheckpointState;
}

export interface ConfigRecordValue {
  value: string | { source: string; fingerprint: string };
  source: string;
}
export interface RunMeta {
  runId: string;
  task: string;
  workspace: string;
  mode: EngineMode;
  /** secrets as fingerprints (§3) */
  config: Record<string, ConfigRecordValue>;
  versions: { jevcode: string; node: string };
  createdAt: string;
  /** appended on resume (§9) */
  overrides: { setting: string; from: string; to: string; atStep: number }[];
  resumes: { resumedAt: string; previousStopReason: StopReason | null }[];
  resolvedJevModel: string | null;
  jevModelDrift: { step: number; served: string } | null;
  /** TUI-DESIGN §15 item 10: the session this run belongs to (default: the run id itself) */
  sessionId?: string;
  /** TUI-DESIGN §15 item 10: the run this one was seeded from (§8.3) */
  parentRunId?: string | null;
  /** TUI-DESIGN §15 item 10 */
  source?: RunSource;
  /** TUI-DESIGN §15 item 10 */
  title?: string;
  /** TUI-DESIGN §15 item 10: scalar replace via updateMeta (run:end re-probe P51, resumedOn P52) */
  git?: RunGitMeta;
  /** TUI-DESIGN §15 item 10: AGENTS.md files folded into the generator system prompt */
  instructions?: InstructionRecord[];
}
/** TUI-DESIGN §15 item 10 */
export type RunSource = 'cli' | 'bench' | 'perf';
/** TUI-DESIGN §15 item 10 */
export interface InstructionRecord {
  path: string;
  sha256: string;
  bytes: number;
}

export interface GeneratorCallRecord {
  step: number;
  attempt: number;
  promptHash: string;
  model: string;
  temperature: number | null;
  maxTokens: number;
  usage: TokenUsage;
  latencyMs: number;
  stopReason: string;
  malformed: boolean;
}

export interface CheckpointStore {
  readonly dir: string;
  create(meta: RunMeta): Promise<void>;
  /** CheckpointError, exit 3 */
  load(): Promise<{ meta: RunMeta; state: CheckpointState; recoveredFrom: 'state' | 'prev' }>;
  /** TUI-DESIGN §15 item 10: patch type gains 'title' | 'instructions' | 'git' (git: scalar replace) */
  updateMeta(patch: Partial<Pick<RunMeta, 'overrides' | 'resumes' | 'resolvedJevModel' | 'jevModelDrift' | 'title' | 'instructions' | 'git'>>): Promise<void>;
  /** write tmp + fsync; rename state.json -> state.prev.json; rename tmp -> state.json */
  writeState(state: CheckpointState): Promise<void>;
  /** synchronous last resort used by shutdown() on a second Ctrl-C or on 'exit' */
  writeStateSync(state: CheckpointState): void;
  appendStep(r: StepRecord): Promise<void>;
  appendDecisions(d: readonly Decision[]): Promise<void>;
  appendJevRequest(r: JevRequestRecord): Promise<void>;
  appendGenerator(g: GeneratorCallRecord): Promise<void>;
  appendTranscript(line: string): Promise<void>;
  /** steps.jsonl records with step > state.step (resume folds them into the window) */
  readStepsAfter(step: number): Promise<StepRecord[]>;
  /** awaited by shutdown() before exit */
  flush(): Promise<void>;
  /** non-fatal warnings (prev fallback, torn steps.jsonl lines) */
  lastWarnings?(): readonly string[];
  /** TUI-DESIGN §15 item 10: ui.json; optional so injected fakes still type-check */
  writeUi?(ui: Json): Promise<void>;
}

// ---------------------------------------------------------------------------------------
// Engine surface
// ---------------------------------------------------------------------------------------

export interface RunLimits {
  maxSteps: number;
  maxWallMs: number;
  maxReplans: number;
  completeThreshold: number;
  impossibleThreshold: number;
  commandTimeoutMs: number;
  maxCommandTimeoutMs: number;
  maxOutputBytes: number;
  spendCapUsd: number;
  /** TUI-DESIGN §15 item 11: only under allowUnpriced; reaching it stops with 'token_cap' */
  maxGeneratorTokens?: number;
}

// TUI-DESIGN §15 item 11: session seeding, clamps and blocking pauses
export interface EngineSeed {
  parentRunId: string;
  /** done/remaining/unverified from the parent (or planAfter of a rewound step); openProblems []; harnessProblems = step-0 human problems (§8.3) */
  plan: Plan;
  /** last 4 of the parent, notes += 'from run <id>' */
  window: WindowEntry[];
  createdThisRun: string[];
  lastTestRun: LastTestRun | null;
  undoLog?: UndoLogEntry[];
  /** @-mentions: boosted into the context candidates, never past the caps */
  pinnedFiles?: string[];
}
/** §9.3: main() emits budget:clamp from it right after run:ready */
export interface SessionClamp {
  runCapUsd: number;
  clampedToUsd: number;
  sessionSpentUsd: number;
  sessionCapUsd: number;
}
export interface SessionRef {
  sessionId: string | null;
  parentRunId: string | null;
  source: RunSource;
  title?: string;
  clamp?: SessionClamp;
}
export type BlockingKind = 'jev-unreachable' | 'key-rejected' | 'spend-limit' | 'checkpoint-degraded' | 'drift' | 'sandbox-unavailable';
export type BlockingAnswer = 'retry' | 'continue' | 'stop' | 'login' | 'pin';
export interface BlockingRequest {
  id: string;
  step: number;
  kind: BlockingKind;
  side?: 'jev' | 'generator';
  detail: string;
  sources?: string[];
  retryInMs?: number;
  stop: StopReason;
  exitCode: number;
}

export interface EngineOptions {
  task: string;
  mode: EngineMode;
  /** realpath is taken by createWorkspace() */
  workspace: string;
  runsDir: string;
  resume?: { runId: string; force: boolean };
  provider: Provider;
  decider: Decider;
  confirmer: Confirmer;
  meter: SpendMeter;
  limits: RunLimits;
  sandboxProfile: SandboxProfile;
  noNetwork: boolean;
  /** masked config for run.json (§3) */
  configRecord: Record<string, ConfigRecordValue>;
  /** redaction function built by resolveConfig (§8.4) */
  redact: (s: string) => string;
  /** secret file paths never read/written (§8) */
  secretPaths: readonly string[];
  /** generator sampling; temperature null = not sent */
  generation: { temperature: number | null; maxTokens: number };
  /** decider model pinning info (§5.4 rule 7) */
  deciderModel: { configured: string; pinned: boolean };
  /** extra directories the sandbox may write to (bench stand-ins for /output etc.); realpath'ed into the profile */
  extraWritableRoots?: readonly string[];
  /** extra directories the sandbox may read but not write (bench object caches) */
  extraReadableRoots?: readonly string[];
  /** jev-only mode: proposes actions with Jev + code search, no generating LLM (required when mode === 'jev-only') */
  synthesizer?: Synthesizer;
  /** injectable clock for perf/unit tests */
  now?: () => number;
  /** injected exit for tests of the forced second Ctrl-C path (TUI-DESIGN §13.4: always injected by cli/session.ts) */
  exit?: (code: number) => never;
  /** TUI-DESIGN §15 item 11: follow-up seed from the parent run (§8.3) */
  seed?: EngineSeed;
  /** TUI-DESIGN §15 item 11: an initial pending directive consumed at the first step start exactly like a steer: typed while `starting`, or the /undo note on /resume (§12.4) */
  humanDirective?: string;
  /** TUI-DESIGN §15 item 11: /resume after /undo or /rewind: merged into the restored undoLog (§12.4) */
  undoLog?: UndoLogEntry[];
  /** TUI-DESIGN §15 item 11: written into run.json; default { sessionId: null -> runId, parentRunId: null, source: 'cli' }; bench/conditions.ts passes source 'bench', the perf drivers `--source perf` */
  session?: SessionRef;
  /** TUI-DESIGN §15 item 11: AGENTS.md: text -> generator system prompt only; files -> run.json.instructions[] */
  instructions?: { files: InstructionRecord[]; text: string };
  /** TUI-DESIGN §15 item 11: count for the run:start secret-ack item (never values) */
  secretsAcked?: number;
  /** TUI-DESIGN §15 item 11 */
  allowUnpriced?: boolean;
  /** TUI-DESIGN §15 item 11: every blocking pause (§13.3) is awaited here at the loop top; absent -> every answer is 'stop' (bench, --plain pipe, --no-input, --json) */
  blocker?: (req: BlockingRequest) => Promise<BlockingAnswer>;
  /** TUI-DESIGN §15 item 11: resolved XDG + legacy jevcode config dirs -> seatbelt read denies (§12.7) */
  configDirs?: readonly string[];
  // NOT here: git / gitDir / gitCommonDir — probed inside createEngine before createSandbox and handed to createWorkspace (§12.1)
}

// ---------------------------------------------------------------------------------------
// Jev-only synthesis (docs/JEV-ONLY.md): code proposes, Jev decides, tests verify
// ---------------------------------------------------------------------------------------

export interface SynthesisContext {
  runId: string;
  /** absolute path of the run directory (shadow lanes, traces live under <runDir>/synth/) */
  runDir: string;
  step: number;
  task: string;
  plan: Plan;
  window: readonly WindowEntry[];
  intent: Intent;
  /** files the context stage selected (path -> content view) */
  contextFiles: readonly FileView[];
  workspace: Workspace;
  workspaceInfo: WorkspaceInfo;
  sandbox: Sandbox;
  decider: Decider;
  signal: AbortSignal;
  limits: RunLimits;
  redact: (s: string) => string;
  /** emit transcript/synth/decision events; the engine redacts and records them */
  emit: (e: EngineEvent) => void;
  /** ask Jev through the engine so usage, decisions.jsonl and the pane stay complete */
  ask: (stage: StageName, state: Json, questions: Record<string, Question>) => Promise<{ answers: Record<string, Answer>; rows: Decision[]; latencyMs: number }>;
  createdThisRun: ReadonlySet<string>;
  /** replan directive text when the loop detector tripped */
  directive: string | null;
  /** opaque synthesizer state restored from the checkpoint (CheckpointState.synthState), null on a fresh run */
  synthState: Json | null;
  /** persist opaque synthesizer state with the next checkpoint (kept small: <= 64 KB after redaction) */
  setSynthState: (state: Json | null) => void;
}

export interface Synthesizer {
  readonly name: string;
  /** Produce exactly one proposal (usually a `patch` or `edit`, sometimes `run`/`read`/`done`) without any generating LLM. */
  synthesize(ctx: SynthesisContext): Promise<Proposal>;
}

export interface EngineStatus {
  step: number;
  maxSteps: number;
  wallMs: number;
  maxWallMs: number;
  stage: StageName | 'idle';
  spend: SpendSnapshot;
  stopReason: StopReason | null;
  /** TUI-DESIGN §15 item 13 */
  maxReplans?: number;
  /** TUI-DESIGN §15 item 13 */
  replans?: number;
  /** TUI-DESIGN §15 item 13: pause() requested, run:end pending at the next loop top */
  pausing?: boolean;
  /** TUI-DESIGN §15 item 13: number of queued steers */
  pendingDirectives?: number;
  /** TUI-DESIGN §15 item 13: the blocking pause awaiting an answer (§13.3) */
  blocked?: BlockingKind | null;
  /** TUI-DESIGN §15 item 13: the active retry sleep (§13.2) */
  retrying?: { side: 'jev' | 'generator'; attempt: number; maxAttempts: number; untilMs: number } | null;
  /** TUI-DESIGN §15 item 13: generator tokens used against RunLimits.maxGeneratorTokens */
  generatorTokens?: { used: number; cap: number | null };
}

// TUI-DESIGN §15 item 14: notices and renderer labels
export type NoticeKind = 'offline' | 'online' | 'checkpoint:degraded' | 'checkpoint:restored' | 'sandbox' | 'drift' | 'seeded' | 'instructions' | 'config' | 'pricing' | 'lock' | 'ui';
/** the only labels formatTranscriptItem prints instead of stepLabel() (item 19, §15.1) */
export type UiLabel = '[ui]' | '[setup]' | '[config]' | '[sandbox]';

export type EngineEvent =
  | { type: 'synth'; step: number; phase: string; detail: string; candidates?: number; tested?: number } // jev-only synthesizer progress
  | { type: 'run:start'; runId: string; task: string; mode: EngineMode; resumedFromStep: number | null }
  // TUI-DESIGN §15 item 14: optional session fields, built as `{ …, sessionId: session?.sessionId ?? runId, parentRunId: session?.parentRunId ?? null }`
  | { type: 'run:ready'; runId: string; step: number; maxSteps: number; task: string; resumed: boolean; sessionId?: string; parentRunId?: string | null; sandbox?: SandboxLevel; noNetwork?: boolean; maxReplans?: number }
  | { type: 'step:start'; step: number; startedAt: string }
  | { type: 'stage:start'; step: number; stage: StageName }
  | { type: 'stage:end'; step: number; stage: StageName; ms: number }
  | { type: 'decision'; decision: Decision }
  | { type: 'jev:request'; record: JevRequestRecord }
  | { type: 'intent'; step: number; intent: Intent; answer: IntentAnswer; probability: number; confidence: number }
  | { type: 'context'; step: number; files: string[]; bytes: number; candidates: number }
  | { type: 'generator:start'; step: number; attempt: number }
  | { type: 'generator:delta'; step: number; text: string }
  | { type: 'generator:tool-delta'; step: number; chars: number } // cumulative streamed tool-argument chars ("streaming action… N chars")
  | { type: 'generator:end'; step: number; usage: TokenUsage; latencyMs: number; finishReason: string }
  | { type: 'proposal'; step: number; proposal: Proposal }
  | { type: 'risk'; step: number; risk: RiskAssessment }
  | { type: 'confirm:request'; request: ConfirmRequest }
  | { type: 'confirm:resolved'; step: number; id: string; approved: boolean; aborted: boolean; note?: string } // TUI-DESIGN §15 item 14: note from confirmDetailed
  | { type: 'exec:start'; step: number; action: Action }
  | { type: 'exec:output'; step: number; stream: 'stdout' | 'stderr'; chunk: string }
  | { type: 'outcome'; step: number; outcome: ActionOutcome }
  | { type: 'judge'; step: number; judge: JudgeResult | null; completion: number | null }
  | { type: 'plan'; step: number; plan: Plan; rejectedDone: string[]; unverifiedDone: string[] }
  | { type: 'loop:tripped'; step: number; signature: string; occurrences: number }
  | { type: 'replan'; step: number; directive: ReplanDirective }
  | { type: 'checkpoint'; step: number; ms: number }
  | { type: 'step:end'; record: StepRecord }
  | { type: 'status'; status: EngineStatus }
  | { type: 'transcript'; step: number | null; level: 'info' | 'warn' | 'error'; text: string }
  | { type: 'error'; step: number | null; error: SerializedError; fatal: boolean }
  | { type: 'run:end'; result: RunResult; exitCode?: number; resumable?: boolean; paths?: { runDir: string; transcript: string; log: string } } // TUI-DESIGN §15 item 14: optional fields
  // TUI-DESIGN §15 item 14: new members (the `synth` member is NOT extended here: its structured fields are the synth team's optional extension)
  | { type: 'steer:queued'; step: number; index: number; text: string; queued: number }
  | { type: 'steer:applied'; step: number; count: number; superseded: string[] }
  | { type: 'steer:withdrawn'; step: number; index: number }
  | { type: 'pause:requested'; step: number }
  | { type: 'budget:warn'; scope: 'run' | 'session'; pct: 50 | 80 | 95; spentUsd: number; capUsd: number; step: number; stepsLeftEstimate: number | null; restored: boolean; jevShare?: { jevUsd: number; generatorUsd: number } }
  | { type: 'budget:stop'; scope: 'run' | 'session'; by: 'run' | 'session' | 'tokens'; spentUsd: number; capUsd: number; step: number; at: StoppedAt; raise: { command: string; flag: string; minimum: number } } // the follow-up refusal is a controller line (§9.3, §8.9), not an event
  | { type: 'budget:clamp'; runCapUsd: number; clampedToUsd: number; sessionSpentUsd: number; sessionCapUsd: number } // emitted by main() after run:ready from EngineOptions.session.clamp (§9.3)
  | { type: 'budget:override'; setting: string; from: string; to: string; appliesTo: 'resume'; source: '/budget' | 'flag' } // emitted by main() per run.json.overrides[] entry recorded on this resume (§9.4)
  | { type: 'budget:unpriced'; side: SpendSource; model: string; step: number; tokens: { input: number; output: number } }
  | { type: 'retry'; side: 'jev' | 'generator'; step: number | null; stage: StageName | null; info: RetryInfo }
  | { type: 'retry:settled'; side: 'jev' | 'generator'; step: number | null; attempts: number; ok: boolean; totalWaitMs: number }
  | { type: 'notice'; step: number | null; kind: NoticeKind; level: 'info' | 'warn' | 'error'; text: string; detail?: string; label?: UiLabel } // kind 'ui' + label = Engine.annotate() (§15.1); detail is the TUI-only body
  | { type: 'workspace'; git: RunGitMeta; instructions: InstructionRecord[]; sandbox: SandboxLevel }
  | { type: 'blocking:request'; request: BlockingRequest }
  | { type: 'blocking:resolved'; id: string; answer: BlockingAnswer; auto: boolean } // auto = the jev-unreachable timer answered
  | { type: 'secret-ack'; step: number | null; count: number };

export type EngineEventType = EngineEvent['type'];

export interface EngineEmitter {
  on<T extends EngineEventType>(type: T, fn: (e: Extract<EngineEvent, { type: T }>) => void): () => void;
  onAny(fn: (e: EngineEvent) => void): () => void;
  emit(e: EngineEvent): void;
}

/** TUI-DESIGN §15 item 15 */
export type SteerResult = { ok: true; index: number; queued: number } | { ok: false; reason: 'empty' | 'full' | 'finished'; queued: number };

export interface Engine {
  readonly runId: string;
  readonly events: EngineEmitter;
  /** the run-level AbortSignal every generate/ask/sandbox run receives */
  readonly signal: AbortSignal;
  /** resolves for every StopReason including 'error'; never rejects */
  run(): Promise<RunResult>;
  /**
   * idempotent; see §11 shutdown(). TUI-DESIGN §15 item 15 (widened): 'error' stores opts.error as the fatal error
   * (fatalExit, §13.4); opts.signal names the signal for exit codes 130 / 143 / 129 (§13.5)
   */
  abort(reason: 'human_abort' | 'signal' | 'error', opts?: { signal?: SignalName; error?: SerializedError }): void;
  status(): EngineStatus;
  /** current checkpoint state for the synchronous last-resort write (§11) */
  snapshotState(): CheckpointState | null;
  /** TUI-DESIGN §15 item 15: queue a human directive for the next step start (<= 8 x 600 chars; raw in memory, masked on every artefact) */
  steer(text: string, opts?: { secretsAcked?: number }): SteerResult;
  /** TUI-DESIGN §15 item 15: withdraw the newest queued directive; null when none */
  unsteer(): PendingDirective | null;
  /** TUI-DESIGN §15 item 15: stop with 'human_pause' at the next §9.1 rule-1 point; idempotent */
  pause(): void;
  /** TUI-DESIGN §15 item 15: end the current retry sleep early (F12 `[r]`); false when no retry sleep is active */
  retryNow(): boolean;
  /** TUI-DESIGN §15 item 15: a renderer-originated transcript line while the run is live (§15.1); false once finished, then the renderer keeps it local */
  annotate(text: string, opts?: { detail?: string; label?: UiLabel; level?: 'info' | 'warn' | 'error' }): boolean;
}

// ---------------------------------------------------------------------------------------
// Renderer (TUI or plain), wired by cli/main.tsx
// ---------------------------------------------------------------------------------------

// TUI-DESIGN §15 item 16: launch settings fixed at mount; session settings through the full chain after firstFrame() (§16)
/** resolveLaunchSettings(flags, env): flag > env > default; pure; no file */
export interface LaunchSettings {
  fps: number;
  renderMode: 'standard' | 'incremental';
  screenReader: boolean;
  ascii: boolean;
  noColor: boolean;
}
/** the LaunchSettings members repeat the mount-time values (source flag | env | default only) */
export interface UiConfig extends LaunchSettings {
  theme: 'dark' | 'light' | 'daltonized' | 'ansi';
  title: boolean;
  reducedMotion: boolean;
  notify: boolean;
  osc52: boolean;
  history: boolean;
  noInput: boolean;
  trustWorkspace: boolean;
  budgetWarnings: boolean;
  allowSecretMention: boolean;
  exitCode: 'zero' | 'last-run';
  logLevel: 'error' | 'warn' | 'info' | 'debug' | 'trace';
  logFile: string | null;
  keybindingsFile: string | null;
}
/**
 * TUI-DESIGN §15 item 19 / §10.1: one detected secret span. Declared here so SessionHost is self-contained;
 * core/redact.ts (O7) exports `detectSecrets` returning this shape.
 */
export interface SecretHit {
  family: string;
  label: string;
  start: number;
  end: number;
  warnOnly: boolean;
}
/** implemented by cli/session.ts over config.redact / config.addSecret; the renderer calls it, never the engine directly */
export interface SessionHost {
  /** addSecret('composer#n', span) per span BEFORE createEngine (§10.2) */
  submit(text: string, opts: { kind: 'prompt' | 'follow-up'; secretSpans: readonly string[]; pinnedFiles: readonly string[] }): Promise<void>;
  command(line: string): Promise<void>;
  /** addSecret per span BEFORE engine.steer; secretsAcked = spans.length */
  steer(text: string, opts: { secretSpans: readonly string[] }): SteerResult;
  unsteer(): PendingDirective | null;
  pause(): void;
  abort(reason: 'human_abort'): void;
  retryNow(): boolean;
  /** a renderer-originated line: engine.annotate() while a run is live, else a local `[ui]` item + `--json` `ui` line (§15.1) */
  note(text: string, opts?: { detail?: string; label?: UiLabel; level?: 'info' | 'warn' | 'error' }): void;
  redact(s: string): string;
  addSecret(name: string, value: string): boolean;
  /** §10.2; before setHost the composer detects with patternRedact only and holds Enter (§4.9) */
  detectSecrets(s: string): readonly SecretHit[];
  exit(code: number): void;
  index(): readonly SessionRow[];
  history(): HistoryStore | null;
  /** pre-run: files.ts listCandidates() once after firstFrame(); from run:ready: the live workspace.listCandidates() (§5.4) */
  workspaceCandidates(): Promise<readonly Candidate[]>;
}
export interface RunRow {
  runId: string;
  parentRunId: string | null;
  startedAt: string;
  endedAt: string | null;
  stopReason: StopReason | null;
  steps: number | null;
  costUsd: { generator: number; jev: number } | null;
  exitCode: number | null;
  resumable: boolean | null;
  resumes: number;
  live: boolean;
}
export interface SessionRow {
  sessionId: string;
  workspace: string;
  title: string;
  task60: string;
  runs: RunRow[];
  lastUsed: string;
  createdAt: string;
  totalUsd: number;
  mode: EngineMode;
  branch: string | null;
}
export interface HistoryStore {
  entries(filter: 'workspace' | 'all'): readonly string[];
  append(kind: 'prompt' | 'steer' | 'command', text: string): void;
  clear(): void;
}

export interface RendererOptions {
  /** task text (or "resuming <run-id>") shown in the first frame */
  task: string;
  resumeId: string | null;
  /** called on Ctrl-C (TUI) / readline SIGINT (plain) */
  onAbort: (reason: 'human_abort' | 'signal') => void;
  stdout?: NodeJS.WriteStream;
  stdin?: NodeJS.ReadStream;
  /** plain mode when stdin is not a TTY: decline after this many ms (default 0 = immediately) */
  confirmTimeoutMs?: number;
  /** TUI-DESIGN §15 item 16 */
  mode?: 'one-shot' | 'session';
  /** TUI-DESIGN §15 item 16: fixed at mount; `ui` (UiConfig) arrives through setUi() after resolveConfig */
  launch?: LaunchSettings;
  /** TUI-DESIGN §15 item 16 */
  host?: SessionHost;
}
export interface Renderer {
  readonly confirmer: Confirmer;
  /** subscribe to engine events; may be called after the first frame */
  attach(engine: Engine): void;
  /** resolves after Ink has flushed the first frame (perf hook) */
  firstFrame(): Promise<void>;
  unmount(): Promise<void>;
  /** TUI-DESIGN §15 item 16: after firstFrame() + resolveConfig; a held submission flushes here (§4.9) */
  setHost?(host: SessionHost): void;
  /** TUI-DESIGN §15 item 16: session settings; theme / notify / … apply to new items and the dynamic region only */
  setUi?(ui: UiConfig): void;
  /** TUI-DESIGN §15 item 16: appends a local item — idle time only (§15.1) */
  notify?(text: string, opts?: { level?: 'info' | 'warn' | 'error'; detail?: string; label?: UiLabel }): void;
}

// ---------------------------------------------------------------------------------------
// Resolved configuration (config/*; consumed by cli/main.tsx)
// ---------------------------------------------------------------------------------------

// TUI-DESIGN §15 item 17: 'ignored:launch' = a file key for a launch setting (§16)
export type ConfigSource = 'flag' | 'env' | `dotenv:${string}` | `file:${string}` | 'default' | 'run.json' | 'wizard' | 'derived' | 'session:/budget' | 'ignored:launch';
/** TUI-DESIGN §15 item 17 */
export type SecretSettingName = 'generator.apiKey' | 'decider.apiKey';

export interface Resolved<T> {
  value: T;
  source: ConfigSource;
}

export interface GeneratorConfig {
  provider: 'anthropic' | 'openrouter';
  model: string;
  apiKey: string;
  baseUrl: string;
  temperature: number | null;
  maxTokens: number;
  /** USD per million tokens, used when the API returns no cost */
  pricing: { inputPerM: number; outputPerM: number; cacheReadPerM: number; cacheWritePerM: number };
  /** TUI-DESIGN §15 item 17: OPTIONAL: validateGenerator always sets it; resolveConfig / validate.ts treat absent as false */
  priced?: boolean;
}

export interface DeciderConfig {
  baseUrl: string;
  apiKey: string;
  /** configured id, verbatim */
  model: string;
  /** normalised id ends in -YYYYMMDD */
  pinned: boolean;
}

export interface ResolvedConfig {
  /** every setting with its source; secrets appear only as fingerprints in record() */
  readonly entries: ReadonlyMap<string, Resolved<string>>;
  /** validates the generator section on first call; ConfigError names setting and sources */
  generator(): GeneratorConfig;
  /** validates the decider section on first call */
  decider(): DeciderConfig;
  limits(): RunLimits;
  workspace: string;
  runsDir: string;
  openAssistPath: string | null;
  configFile: string | null;
  /** dotenv files that were actually read */
  dotenvFiles: readonly string[];
  sandbox: SandboxProfile;
  noNetwork: boolean;
  plain: boolean;
  /** secret file paths (dotenvs, config file) for the sandbox read-deny list and SecretPathError */
  secretPaths: readonly string[];
  /** redaction built from the SecretSet (§8.4) */
  redact: (s: string) => string;
  redactJson: (v: Json) => Json;
  /** masked table for run.json and `jevcode config` */
  record(): Record<string, ConfigRecordValue>;
  // TUI-DESIGN §15 item 17 — OPTIONAL in contract 1.1 wave 0 (config/resolve.ts does not implement them yet); O6 makes them
  // required in wave 1 together with the implementations (missingSecrets, ui, sessionSpendCap, addSecret, dropSecret, configDirs).
  /** non-throwing; skips generator.apiKey for jev-only and --mock* */
  missingSecrets?(mode: EngineMode): readonly SecretSettingName[];
  /** session settings through the full chain; the launch members are copied from the argument, never re-resolved */
  ui?(launch: LaunchSettings): UiConfig;
  /** 'none' -> +Infinity */
  sessionSpendCap?(mode: EngineMode): { value: number; source: ConfigSource; derived: boolean };
  /** delegate to the redactor */
  addSecret?(name: string, value: string): boolean;
  dropSecret?(name: string): boolean;
  /** resolved XDG + legacy jevcode dirs (§12.7) */
  readonly configDirs?: readonly string[];
}

// ---------------------------------------------------------------------------------------
// Bench records (bench/*)
// ---------------------------------------------------------------------------------------

export type BenchSuite = 'swebench' | 'terminal-bench' | 'quixbugs' | 'ladder'; // quixbugs/ladder: the jev-only difficulty ladder (docs/JEV-ONLY.md)
export type BenchEvaluator = 'local-venv' | 'invalid' | 'local' | 'mock' | 'none';
export type BenchStopReason = StopReason | 'not_run';

export interface BenchTaskRecord {
  suite: BenchSuite;
  task: string;
  condition: EngineMode;
  pass: boolean | null;
  evaluator: BenchEvaluator;
  reason?: string;
  steps: number;
  wallMs: number;
  /** combined generator + Jev tokens per committed step */
  tokensPerStep: number[];
  generatorTokensPerStep: number[];
  jevTokensPerStep: number[];
  cost: { generator: number; jev: number };
  jevLatencyMs: { raw: number[]; p50: number | null; p95: number | null };
  jevRequests: number;
  jevQuestions: number;
  timing: { generatorMs: number; jevMs: number; execMs: number; harnessMs: number };
  stopReason: BenchStopReason;
  blocked: number;
  reviews: number;
  declined: number;
  loops: number;
  replans: number;
  reads: number;
  modelDrift: boolean;
  pairComplete: boolean;
  patchEmpty: boolean | null;
  patchApplied: boolean | null;
  patchBytes: number | null;
  runId: string | null;
  capFired: 'bench' | 'task' | null;
  /** official report.json shape (SWE-bench) */
  testsStatus?: { FAIL_TO_PASS: { success: string[]; failure: string[] }; PASS_TO_PASS: { success: string[]; failure: string[] } };
  evalExitCode?: number | null;
}

// ---------------------------------------------------------------------------------------
// Mock factories (provider/mock.ts, jev/mock.ts) — used by unit tests, perf and the bench
// ---------------------------------------------------------------------------------------

export interface MockTurn {
  /** streamed as text deltas */
  text?: string;
  /** returned as a tool call (the engine prefers this over fenced JSON in `text`) */
  toolCall?: ToolCall;
  usage?: Partial<TokenUsage>;
  latencyMs?: number;
  /** throw a ProviderHttpError with this status instead of answering */
  error?: { status: number; retryable: boolean };
}
export interface MockProviderOptions {
  turns: MockTurn[] | ((req: GenerateRequest, index: number) => MockTurn);
  /** deltas per second when latencyMs > 0 (default 0 = single delta) */
  deltaChunkSize?: number;
  model?: string;
}
export interface MockDeciderContext {
  stage: StageName;
  step: number;
  state: Json;
  questions: Record<string, Question>;
}
/** Return answers for some or all questions; unanswered ids fall through to the default heuristics. */
export type MockDeciderRule = (ctx: MockDeciderContext) => Partial<Record<string, Answer>> | undefined;
export interface MockDeciderOptions {
  rules?: MockDeciderRule[];
  latencyMs?: number;
  model?: string;
  /** throw JevHttpError(status) for calls matching stage/step (every attempt) */
  failAt?: { stage: StageName; step?: number; status: number; times?: number }[];
  /** return a malformed body once at this stage/step (validation path) */
  malformedAt?: { stage: StageName; step?: number; transient: boolean }[];
}

// ---------------------------------------------------------------------------------------
// Factory signatures each module must export (documentation of the wiring surface)
// ---------------------------------------------------------------------------------------
// config/resolve.ts      export function resolveConfig(flags: ParsedFlags, env: NodeJS.ProcessEnv, cwd: string): Promise<ResolvedConfig>
// jev/client.ts          export function createJevDecider(cfg: DeciderConfig, deps: { fetch?: typeof fetch; redact: (s: string) => string; referer?: string }): Decider
// jev/mock.ts            export function createMockDecider(opts?: MockDeciderOptions): Decider
// provider/anthropic.ts  export function createAnthropicProvider(cfg: GeneratorConfig, deps: { fetch?: typeof fetch; redact }): Provider
// provider/openrouter.ts export function createOpenRouterProvider(cfg: GeneratorConfig, deps: { fetch?: typeof fetch; redact }): Provider
// provider/mock.ts       export function createMockProvider(opts: MockProviderOptions): Provider
// provider/null.ts       export function createNullProvider(): Provider   // throws ProviderError if generate() is ever called (jev-only)
// spend/meter.ts         export function createSpendMeter(capUsd: number, parent?: SpendMeter): SpendMeter
// workspace/files.ts     export function createWorkspace(root: string, runDir: string, deps: { sandbox: Sandbox; secretPaths: readonly string[]; redact }): Promise<Workspace>
// sandbox/run.ts         export function createSandbox(opts: { workspaceRoot: string; runDir: string; profile: SandboxProfile; noNetwork: boolean; secretReadDenies: readonly string[]; redact }): Sandbox
// checkpoint/store.ts    export function createCheckpointStore(runsDir: string, runId: string, redact): CheckpointStore
// checkpoint/run-id.ts   export function newRunId(now: Date, random?: () => Buffer): string; export function isValidRunId(id: string): boolean
// loop/engine.ts         export function createEngine(opts: EngineOptions): Promise<Engine>
// loop/generator-only.ts export function createGeneratorOnlyEngine(opts: EngineOptions): Promise<Engine>
// tui/App.tsx            export function createTuiRenderer(opts: RendererOptions): Renderer
// tui/plain.ts           export function createPlainRenderer(opts: RendererOptions): Renderer
// bench/conditions.ts    export const alwaysDecline: Confirmer

// ---------------------------------------------------------------------------------------
// Sandbox factory options and bench dependency injection (added 2026-09-19 for wave-1 decoupling)
// ---------------------------------------------------------------------------------------

export interface SandboxCreateOptions {
  workspaceRoot: string;
  runDir: string;
  profile: SandboxProfile;
  noNetwork: boolean;
  /** absolute paths the seatbelt profile denies reading (dotenvs, config file, ~/.ssh, ...) */
  secretReadDenies: readonly string[];
  redact: (s: string) => string;
  /** additional writable roots beyond the workspace and run dir */
  extraWritable?: readonly string[];
  /** additional read-only roots (e.g. a shared git object cache the workspace's --shared clone points at) */
  extraReadable?: readonly string[];
  /**
   * deny writes to <workspace>/.git/config and .git/hooks (default true: the agent must not plant
   * git-executed code). Bench infrastructure sandboxes that themselves `git clone` into the root pass false.
   */
  protectGit?: boolean;
  /** TUI-DESIGN §15 item 18: the probe's gitDir (moved denies live there; §12.1) */
  gitDir?: string;
  /** TUI-DESIGN §15 item 18: the probe's commonDir for linked worktrees */
  gitCommonDir?: string;
  /** TUI-DESIGN §15 item 18: resolved jevcode config dirs appended to the file-read denies (§12.7) */
  configDirs?: readonly string[];
}

/** Everything the bench runner needs, injected so bench/* compiles and tests without the real modules. */
export interface BenchDeps {
  createEngine(opts: EngineOptions): Promise<Engine>;
  createGeneratorOnlyEngine(opts: EngineOptions): Promise<Engine>;
  createMockProvider(opts: MockProviderOptions): Provider;
  createMockDecider(opts?: MockDeciderOptions): Decider;
  createSpendMeter(capUsd: number, parent?: SpendMeter): SpendMeter;
  createSandbox(opts: SandboxCreateOptions): Sandbox;
  /** present only with --live */
  liveProvider?: Provider;
  liveDecider?: Decider;
}
