#!/usr/bin/env node
// Generates the documentation deliverables of TUI-DESIGN §21 from the registries, so the docs can never
// drift from the code: docs/KEYS.md from KEY_ACTIONS (src/tui/keys/bindings.ts), docs/COMMANDS.md from
// COMMANDS (src/tui/commands/registry.ts), man/jevcode.1 and completions/jevcode.{bash,zsh,fish} from
// cli/args.ts FLAGS + COMMANDS (static scripts; run-id completion is shell-side `ls $JEVCODE_HOME/runs`).
//
//   node scripts/gen-docs.mjs            write every target
//   node scripts/gen-docs.mjs --check    exit 1 and list the targets that are stale (the sync test runs this)
//   node scripts/gen-docs.mjs --print <target>   print one target (keys | commands | man | bash | zsh | fish)
//   node scripts/gen-docs.mjs [--check] --out <dir>   read/write the targets under <dir> instead of the repo root (tests)
//
// The TypeScript registries are loaded through tsx's ESM API (a devDependency), so no build step is needed.
// The man page's .TH date is deterministic so `--check` is stable: SOURCE_DATE_EPOCH (reproducible builds)
// > the commit date of package.json (`git log -1 --format=%cs -- package.json`, the release metadata) > today
// (only when git is unavailable, e.g. an unpacked tarball). Comparisons normalise CRLF so an autocrlf checkout
// never reports every target stale.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TARGETS = {
  keys: 'docs/KEYS.md',
  commands: 'docs/COMMANDS.md',
  man: 'man/jevcode.1',
  bash: 'completions/jevcode.bash',
  zsh: 'completions/jevcode.zsh',
  fish: 'completions/jevcode.fish',
};

/** the .TH date (YYYY-MM-DD): SOURCE_DATE_EPOCH > package.json's last commit date > today */
export function manDate(env = process.env) {
  const epoch = env.SOURCE_DATE_EPOCH;
  if (epoch && /^\d+$/.test(epoch)) return new Date(Number(epoch) * 1000).toISOString().slice(0, 10);
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', 'package.json'], { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], timeout: 10_000 }).trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(out)) return out;
  } catch {
    // no git: fall through
  }
  return new Date().toISOString().slice(0, 10);
}

/** load the registries (TypeScript) through tsx */
export async function loadRegistries() {
  const { register } = await import('tsx/esm/api');
  const unregister = register();
  try {
    const [bindings, registry, args, defaults] = await Promise.all([
      import(pathToFileURL(join(ROOT, 'src/tui/keys/bindings.ts')).href),
      import(pathToFileURL(join(ROOT, 'src/tui/commands/registry.ts')).href),
      import(pathToFileURL(join(ROOT, 'src/cli/args.ts')).href),
      import(pathToFileURL(join(ROOT, 'src/config/defaults.ts')).href),
    ]);
    const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
    return {
      KEY_ACTIONS: bindings.KEY_ACTIONS,
      KEY_CONTEXTS: bindings.KEY_CONTEXTS,
      RESERVED_KEYS: bindings.RESERVED_KEYS,
      displayKey: bindings.displayKey,
      COMMANDS: registry.COMMANDS,
      // TUI-DESIGN-3 §1.1 (D-N): the man page derives its mode line from the table and the one constant — no literal names a default
      ENGINE_MODES: registry.ENGINE_MODES,
      DEFAULT_MODE: defaults.DEFAULT_MODE,
      FLAGS: args.FLAGS,
      CLI_COMMANDS: args.COMMANDS,
      version: pkg.version,
      date: manDate(),
    };
  } finally {
    await unregister();
  }
}

const GENERATED_MD = (source) => `<!-- generated by scripts/gen-docs.mjs from ${source}; do not edit by hand — run \`node scripts/gen-docs.mjs\` -->`;

function mdCell(s) {
  return String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function contextTitle(c) {
  return { global: 'Global', composer: 'Composer', review: 'Review box', picker: 'Session picker', palette: 'Palette' }[c] ?? c;
}

/** docs/KEYS.md */
export function renderKeysMd(r) {
  const lines = [GENERATED_MD('src/tui/keys/bindings.ts KEY_ACTIONS'), '', '# Keys', '', 'Every key is resolved by one pure function over an enumerated state machine (TUI-DESIGN §3), never by handler order. Contexts in precedence order: minsize · overlay · picker · composer · global. Rebind through `${XDG_CONFIG_HOME:-~/.config}/jevcode/keybindings.json` (`--keybindings <file>`, `JEVCODE_KEYBINDINGS`): `{ "namespace:action": "ctrl+g" | ["?", "f1"] | "ctrl+x ctrl+s" | "none" }` — a value with two space-separated keys is a chord completed within 3 s; `"none"`/`null` unbinds; reserved keys and unknown ids are refused with a `jevcode.log` warning, never fatally; `/help reload` re-reads the file.', '', `Reserved and never rebindable (A24): ${r.RESERVED_KEYS.filter((k) => k.startsWith('ctrl+')).map((k) => `\`${r.displayKey(k)}\``).join(', ')} (Enter, Esc and Tab are the same bytes).`, ''];
  for (const ctx of r.KEY_CONTEXTS) {
    const rows = r.KEY_ACTIONS.filter((a) => a.context === ctx);
    if (rows.length === 0) continue;
    lines.push(`## ${contextTitle(ctx)}`, '', '| Action id | Default keys | Does | When | Notes |', '| --- | --- | --- | --- | --- |');
    for (const a of rows) {
      const keys = a.keys.length === 0 ? '_unbound_' : a.keys.map((k) => `\`${r.displayKey(k)}\``).join(', ');
      const notes = [a.reserved ? 'reserved — never rebindable' : '', a.note ?? ''].filter(Boolean).join('; ');
      lines.push(`| \`${a.id}\` | ${keys} | ${mdCell(a.title)} | ${mdCell(a.when ?? '')} | ${mdCell(notes)} |`);
    }
    lines.push('');
  }
  lines.push('## Ctrl-C / Esc / Ctrl-D', '', 'Windows: Ctrl-C ×2 within 1.5 s, Esc Esc within 2 s, Ctrl-D ×2 within 800 ms, Esc re-buffer 30 ms (a letter inside it is the Alt chord). The draft rule outranks the review rule: Ctrl-C with text clears the draft (to history, secrets masked) wherever you are; Ctrl-C with an empty draft aborts a live run (session mode stays, one-shot exits 130) or, under a pending review, aborts the run without committing a decline; Ctrl-C ×2 idle exits 0. Esc pauses a live run at the next step boundary, Esc Esc aborts; on an idle empty composer Esc Esc opens the rewind/steer menu. Ctrl-D with text deletes forward; on an empty composer Ctrl-D ×2 exits 0 (with a live run it asks `a run is live: [y] abort and exit   [n] stay`). See TUI-DESIGN §3.3 for the full matrix.', '');
  return lines.join('\n');
}

/** docs/COMMANDS.md */
export function renderCommandsMd(r) {
  const lines = [GENERATED_MD('src/tui/commands/registry.ts COMMANDS'), '', '# Slash commands', '', 'Type `/` at the start of an empty composer to open the palette; Enter runs a command only when the draft is an exact name or alias and the palette marker is on its own row — otherwise Enter walks the list and Tab puts the highlighted row in the draft (TUI-DESIGN-4 §4.2). A `/` token that matches nothing keeps the draft and appends `[ui] error: /foo — not a command · type / to list commands`, and gains `. Did you mean /budget?` when one of the 41 names or 21 aliases ranks at or above the word-prefix band (§3.1.7; an `(idle only)` / `(live only)` note follows the suggestion when it cannot run now); a submitted line is a paid run. Aliases are shortcuts: `/s` is `/status`, `/m jev-on` is `/mode jev-on`; in the palette an exact alias pins its command to the top and the alias column shows the shortest one (TUI-DESIGN-3 §4.1). `avail`: idle | live | any — an idle-only command while a run is live answers `/x runs when the run is idle; Esc pauses first` (the draft is cleared: nothing to fix); a live-only command while idle answers `/x needs a live run`. `plain`: support in the `--plain` readline composer. Arguments follow TUI-DESIGN §5.1: bare words, `"double quotes"` with `\\` escapes, `\'single quotes\'`; `--flag` and `--flag=value` are options; Tab completes an argument (enum values, settings, changed steps, session titles) and never wipes a typed one.', '', '| Command | Args | avail | plain | Semantics |', '| --- | --- | --- | --- | --- |'];
  for (const c of r.COMMANDS) {
    const names = [`\`/${c.name}\``, ...c.aliases.map((a) => `alias \`/${a}\``)].join(', ');
    const flags = (c.flags ?? []).map((f) => `\`--${f.name}${f.value ? `=${f.values ? f.values.join('|') : '<value>'}` : ''}\` ${f.title}${f.idleOnly ? ' (idle only)' : ''}`).join('; ');
    // TUI-DESIGN-3 §1.1 (D-N): the /mode row names the default from the one constant, never a literal
    const base = c.name === 'mode' ? `${c.semantics} (default ${r.DEFAULT_MODE})` : c.semantics;
    const semantics = flags ? `${base}. Flags: ${flags}` : base;
    lines.push(`| ${names} | ${mdCell(c.usage)} | ${c.availableDuringTask} | ${mdCell(c.plain)} | ${mdCell(semantics)} |`);
  }
  lines.push('', 'Deferred (TUI-DESIGN §22): `/doctor` (CLI `jevcode doctor` first), `/cd`, project commands (A63), `/redo`.', '');
  return lines.join('\n');
}

function roff(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/^([.'])/gm, '\\&$1').replace(/-/g, '\\-');
}

/** mandoc measures input lines after turning every non-ASCII character into `\[uXXXX]` (8 bytes) */
function roffBytes(s) {
  let n = 0;
  for (const ch of s) n += ch.codePointAt(0) < 0x80 ? 1 : 8;
  return n;
}

/** fill an (already escaped) text line into input lines of ≤ 78 bytes (mandoc STYLE: 80-byte input lines); a wrapped line never starts with a control character */
function fill(text, width = 78) {
  const out = [];
  let cur = '';
  for (const word of String(text).split(' ')) {
    if (cur === '') cur = word;
    else if (roffBytes(`${cur} ${word}`) <= width) cur += ` ${word}`;
    else {
      out.push(cur);
      cur = word;
    }
  }
  if (cur !== '') out.push(cur);
  return out.map((l) => l.replace(/^([.'])/, '\\&$1'));
}

/** a body paragraph: escape then fill */
function body(text) {
  return fill(roff(text));
}

const EXIT_CODES = [
  ['0', 'complete / generator_done; /exit, Ctrl\\-D \\(mu)2, Ctrl\\-C \\(mu)2 idle (leaving is not a failure)'],
  ['1', 'uncaught error or an escalated render fault'],
  ['2', 'configuration or usage error at launch; first\\-call 401/403; unpriced model without \\-\\-allow\\-unpriced'],
  ['3', 'checkpoint degraded and stopped (state.json not resumable)'],
  ['4', 'a budget stop (max_steps, wall_time, spend_cap, max_replans, token_cap), replan_stop, impossible, human_pause'],
  ['5', 'API failure after retries; provider spend limit'],
  ['6', 'sandbox or path abort'],
  ['129', 'SIGHUP / EIO'],
  ['130', 'Ctrl\\-C \\(mu)2 while a run is live (one\\-shot) or an external SIGINT'],
  ['143', 'SIGTERM'],
];

/** man/jevcode.1 */
export function renderMan(r) {
  const visible = r.FLAGS.filter((f) => !f.hidden);
  const common = visible.filter((f) => f.commands.length >= 4);
  const L = [];
  L.push(`.\\" generated by scripts/gen-docs.mjs from src/cli/args.ts FLAGS + COMMANDS and src/tui/commands/registry.ts; do not edit by hand`);
  L.push(`.TH JEVCODE 1 "${r.date}" "jevcode ${roff(r.version)}" "User Commands"`);
  L.push('.SH NAME', 'jevcode \\- coding\\-agent harness where Jev decides and the code model writes the code');
  L.push('.SH SYNOPSIS');
  const synopsis = [
    ['.B jevcode', '[\\fIchat\\fR] [\\fIflags\\fR]'],
    ['.B jevcode run', '\\fI<task text>\\fR | \\fB\\-\\-task\\-file\\fR \\fI<path>\\fR | \\fB\\-\\-resume\\fR \\fI<id|title>\\fR [\\fIflags\\fR]'],
    ...r.CLI_COMMANDS.filter((c) => c !== 'run' && c !== 'chat').map((c) => [`.B jevcode ${roff(c)}`, '[\\fIflags\\fR]']),
  ];
  // `.br` only between synopsis lines — a trailing one is a mandoc WARNING (paragraph macro at the end of SH)
  synopsis.forEach((lines, n) => L.push(...lines, ...(n < synopsis.length - 1 ? ['.br'] : [])));
  L.push('.SH DESCRIPTION');
  L.push(...fill('A bare \\fBjevcode\\fR opens the interactive session TUI: a scrollback\\-native transcript, a composer, the Jev decision pane and a status line. \\fBjevcode run\\fR runs one task and exits with the run\\(aqs code. Every human decision (approve, decline, steer, pause, abort) is a key or a slash command; keys never appear in logs, secrets are detected at every entry point and the sandbox confines every command the generator proposes.'));
  L.push('.SH COMMANDS');
  const cliDesc = {
    chat: 'interactive session (the default when no command is given)',
    run: 'run one task; \\-\\-resume continues a stored run',
    config: 'print the resolved configuration with the source of every value',
    bench: 'run the benchmark suites',
    perf: 'run the performance gates',
    login: 'store an API key (masked prompt or \\-\\-*\\-stdin)',
    logout: 'remove a stored API key',
    sessions: 'list, reindex, prune or unlock sessions',
    report: 'write a redacted support bundle for a run',
    why: 'explain one Jev decision of a stored run',
    calibration: 'reliability report over this workspace\\(aqs runs',
    completion: 'print the shell completion script (bash|zsh|fish)',
    upgrade: 'upgrade through the detected package manager',
  };
  for (const c of r.CLI_COMMANDS) L.push('.TP', `.B ${roff(c)}`, ...fill(cliDesc[c] ?? ''));
  L.push('.SH OPTIONS', 'Common flags (every command):');
  for (const f of common) L.push('.TP', `.BI \\-\\-${roff(f.name)}${f.arg ? ` " ${roff(f.arg)}"` : ''}`, ...body(f.help));
  for (const c of r.CLI_COMMANDS) {
    const own = visible.filter((f) => f.commands.includes(c) && f.commands.length < 4 && f.key !== 'help' && f.key !== 'version');
    if (own.length === 0) continue;
    L.push('.PP', `Flags of \\fB${roff(c)}\\fR:`);
    for (const f of own) L.push('.TP', `.BI \\-\\-${roff(f.name)}${f.arg ? ` " ${roff(f.arg)}"` : ''}`, ...body(f.help));
  }
  L.push('.SH INTERACTIVE COMMANDS', ...fill('Typed at the composer; Enter runs a command only on an exact name or alias match with the palette marker on its own row (otherwise Enter walks the list and Tab picks). avail: idle | live | any.'));
  for (const c of r.COMMANDS) {
    const names = [`/${c.name}`, ...c.aliases.map((a) => `/${a}`)].join(', ');
    L.push('.TP', `.B ${roff(names)}${c.usage !== '—' ? ` \\fI${roff(c.usage)}\\fR` : ''}`, ...fill(`${roff(c.title)} (${c.availableDuringTask})`));
  }
  L.push('.SH KEYS');
  for (const ctx of r.KEY_CONTEXTS) {
    const rows = r.KEY_ACTIONS.filter((a) => a.context === ctx && a.keys.length > 0);
    if (rows.length === 0) continue;
    L.push(`.SS ${roff(contextTitle(ctx))}`);
    for (const a of rows) L.push('.TP', `.B ${roff(a.keys.map((k) => r.displayKey(k, true)).join(', '))}`, ...body(a.title));
  }
  L.push('.SH EXIT STATUS');
  for (const [code, text] of EXIT_CODES) L.push('.TP', `.B ${code}`, ...fill(text));
  L.push('.SH FILES');
  const files = [
    ['~/.jevcode/runs/<run-id>/', 'run directory: run.json, state.json, steps.jsonl, transcript.log, jevcode.log, pre/, post/, ui.json'],
    ['~/.jevcode/sessions/index.jsonl', 'the session index'],
    ['~/.jevcode/history.jsonl', 'composer history (redacted, 1,000 entries)'],
    ['~/.jevcode/trust.json', 'workspace trust decisions'],
    ['${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json', 'configuration and stored keys (mode 0600)'],
    ['${XDG_CONFIG_HOME:-~/.config}/jevcode/keybindings.json', 'key rebindings (namespace:action → key, chord or "none")'],
    ['./jevcode.json, ./.env', 'per\\-workspace configuration and dotenv fallback'],
  ];
  for (const [p, d] of files) L.push('.TP', `.I ${roff(p)}`, ...fill(d));
  L.push('.SH ENVIRONMENT');
  const env = [
    ['TYPESAFE_API_KEY, OPENROUTER_API_KEY, JEV_API_KEY, ANTHROPIC_API_KEY', 'decider (Jev) and generator keys; jev\\-only needs one Jev key'],
    ['JEVCODE_MODE, JEV_PROVIDER', `engine mode (${r.ENGINE_MODES.map((m) => roff(m)).join(' | ')}; default ${roff(r.DEFAULT_MODE)}) and Jev provider (auto | typesafe | openrouter)`],
    ['JEVCODE_HOME', 'root of runs/, sessions/ and history (default ~/.jevcode)'],
    ['JEVCODE_CONFIG, JEVCODE_KEYBINDINGS', 'configuration and keybindings file paths'],
    ['JEVCODE_SPEND_CAP_USD, JEVCODE_SESSION_SPEND_CAP_USD', 'run and session spend caps'],
    ['JEVCODE_THEME, JEVCODE_FPS, JEVCODE_ASCII, JEVCODE_SCREEN_READER, JEVCODE_REDUCED_MOTION', 'UI settings (flag > env > file > default)'],
    ['JEVCODE_LOG, JEVCODE_LOG_LEVEL, JEVCODE_TRACE', 'log file and level (keys never appear in logs)'],
    ['NO_COLOR, FORCE_COLOR', 'colour control'],
    ['CI, TERM=dumb', 'select the plain renderer'],
  ];
  for (const [v, d] of env) L.push('.TP', `.B ${roff(v)}`, ...fill(d));
  L.push('.SH SEE ALSO', 'docs/TUI-DESIGN.md, docs/KEYS.md, docs/COMMANDS.md in the source tree.');
  return L.join('\n') + '\n';
}

function flagsFor(r, cmd) {
  return r.FLAGS.filter((f) => !f.hidden && f.commands.includes(cmd));
}

function shQuote(s) {
  return `'${String(s).replace(/'/g, `'\\''`)}'`;
}

/** completions/jevcode.bash */
export function renderBash(r) {
  const L = ['# bash completion for jevcode — generated by scripts/gen-docs.mjs from src/cli/args.ts; do not edit by hand', '# install: jevcode completion bash > ~/.local/share/bash-completion/completions/jevcode', ''];
  L.push('_jevcode() {', '  local cur prev cmd words', '  COMPREPLY=()', '  cur="${COMP_WORDS[COMP_CWORD]}"', '  prev="${COMP_WORDS[COMP_CWORD-1]}"', '  cmd=""', '  local i', '  for ((i = 1; i < COMP_CWORD; i++)); do', '    case "${COMP_WORDS[i]}" in', `      ${r.CLI_COMMANDS.join('|')}) cmd="\${COMP_WORDS[i]}"; break ;;`, '    esac', '  done');
  L.push('  case "$prev" in', '    --resume)', '      local runs="${JEVCODE_HOME:-$HOME/.jevcode}/runs"', '      [ -d "$runs" ] && COMPREPLY=( $(compgen -W "$(ls "$runs" 2>/dev/null)" -- "$cur") )', '      return 0 ;;');
  const enums = new Map();
  for (const f of r.FLAGS) if (!f.hidden && f.arg && /^[a-z0-9-]+(\|[a-z0-9-]+)+$/.test(f.arg)) enums.set(f.name, f.arg.split('|'));
  for (const [name, values] of enums) L.push(`    --${name}) COMPREPLY=( $(compgen -W ${shQuote(values.join(' '))} -- "$cur") ); return 0 ;;`);
  L.push('    --task-file|--config|--out) COMPREPLY=( $(compgen -f -- "$cur") ); return 0 ;;', '    --workspace|--runs-dir|--open-assist-path) COMPREPLY=( $(compgen -d -- "$cur") ); return 0 ;;', '  esac');
  L.push('  if [ -z "$cmd" ]; then', `    COMPREPLY=( $(compgen -W ${shQuote([...r.CLI_COMMANDS, '--help', '--version'].join(' '))} -- "$cur") )`, '    return 0', '  fi', '  case "$cmd" in');
  for (const c of r.CLI_COMMANDS) L.push(`    ${c}) COMPREPLY=( $(compgen -W ${shQuote(flagsFor(r, c).map((f) => `--${f.name}`).join(' '))} -- "$cur") ) ;;`);
  L.push('  esac', '  return 0', '}', 'complete -F _jevcode jevcode', '');
  return L.join('\n');
}

/** completions/jevcode.zsh */
export function renderZsh(r) {
  const L = ['#compdef jevcode', '# zsh completion for jevcode — generated by scripts/gen-docs.mjs from src/cli/args.ts; do not edit by hand', '# install: jevcode completion zsh > ~/.zsh/completions/_jevcode  (with fpath+=~/.zsh/completions)', ''];
  L.push('_jevcode_runs() {', '  local runs="${JEVCODE_HOME:-$HOME/.jevcode}/runs"', '  [[ -d "$runs" ]] && _values "run id" ${runs}/*(N:t)', '}', '');
  L.push('_jevcode() {', '  local -a commands', '  commands=(');
  const cliDesc = { chat: 'interactive session', run: 'run one task', config: 'print the resolved configuration', bench: 'run the benchmark suites', perf: 'run the performance gates', login: 'store an API key', logout: 'remove a stored API key', sessions: 'list or maintain sessions', report: 'write a support bundle', why: 'explain a Jev decision', calibration: 'reliability report', completion: 'print a completion script', upgrade: 'upgrade jevcode' };
  for (const c of r.CLI_COMMANDS) L.push(`    ${shQuote(`${c}:${cliDesc[c] ?? c}`)}`);
  L.push('  )', '  _arguments -C \\', `    '1:command:->cmd' \\`, `    '*::arg:->args'`, '  case "$state" in', '    cmd) _describe -t commands "jevcode command" commands ;;', '    args)', '      case "${words[1]}" in');
  for (const c of r.CLI_COMMANDS) {
    L.push(`        ${c})`, '          _arguments \\');
    const specs = flagsFor(r, c).map((f) => {
      let action = '';
      // TUI-DESIGN-2 §1.4: a per-command value list (`--jev-provider typesafe|openrouter` on login) narrows the enum
      const arg = f.argFor?.[c] ?? f.arg;
      if (f.name === 'resume') action = ':run id:_jevcode_runs';
      else if (arg && /^[a-z0-9-]+(\|[a-z0-9-]+)+$/.test(arg)) action = `:${f.name}:(${arg.split('|').join(' ')})`;
      else if (/file|path|config|out/.test(f.name)) action = `:${f.arg ?? 'file'}:_files`;
      else if (/dir|workspace/.test(f.name)) action = `:${f.arg ?? 'dir'}:_files -/`;
      else if (f.arg) action = `:${f.arg.replace(/[<>]/g, '')}:`;
      return `            ${shQuote(`--${f.name}[${f.help.replace(/[\[\]]/g, ' ')}]${action}`)}`;
    });
    L.push(specs.join(' \\\n') + (c === 'run' ? ` \\\n            '*:task text:'` : ''), '          ;;');
  }
  L.push('      esac ;;', '  esac', '}', '', '_jevcode "$@"', '');
  return L.join('\n');
}

/** completions/jevcode.fish */
export function renderFish(r) {
  const L = ['# fish completion for jevcode — generated by scripts/gen-docs.mjs from src/cli/args.ts; do not edit by hand', '# install: jevcode completion fish > ~/.config/fish/completions/jevcode.fish', ''];
  L.push('function __jevcode_runs', '  set -l runs (set -q JEVCODE_HOME; and echo $JEVCODE_HOME; or echo $HOME/.jevcode)/runs', '  test -d $runs; and ls $runs', 'end', '');
  const cliDesc = { chat: 'interactive session', run: 'run one task', config: 'print the resolved configuration', bench: 'run the benchmark suites', perf: 'run the performance gates', login: 'store an API key', logout: 'remove a stored API key', sessions: 'list or maintain sessions', report: 'write a support bundle', why: 'explain a Jev decision', calibration: 'reliability report', completion: 'print a completion script', upgrade: 'upgrade jevcode' };
  L.push(`complete -c jevcode -f`);
  for (const c of r.CLI_COMMANDS) L.push(`complete -c jevcode -n '__fish_use_subcommand' -a ${c} -d ${shQuote(cliDesc[c] ?? c)}`);
  for (const f of r.FLAGS) {
    if (f.hidden) continue;
    const cond = `__fish_seen_subcommand_from ${f.commands.join(' ')}`;
    let extra = '';
    if (f.type === 'string') {
      if (f.name === 'resume') extra = ` -x -a '(__jevcode_runs)'`;
      else if (f.arg && /^[a-z0-9-]+(\|[a-z0-9-]+)+$/.test(f.arg)) extra = ` -x -a ${shQuote(f.arg.split('|').join(' '))}`;
      else if (/file|config|out/.test(f.name)) extra = ' -r -F';
      else if (/dir|workspace/.test(f.name)) extra = ' -x -a \'(__fish_complete_directories)\'';
      else extra = ' -x';
    }
    L.push(`complete -c jevcode -n ${shQuote(cond)} -l ${f.name}${extra} -d ${shQuote(f.help)}`);
  }
  L.push('');
  return L.join('\n');
}

/** every target's rendered text */
export function renderAll(r) {
  return { keys: renderKeysMd(r), commands: renderCommandsMd(r), man: renderMan(r), bash: renderBash(r), zsh: renderZsh(r), fish: renderFish(r) };
}

async function main(argv) {
  const r = await loadRegistries();
  const all = renderAll(r);
  if (argv.includes('--print')) {
    const which = argv[argv.indexOf('--print') + 1];
    if (!(which in all)) {
      process.stderr.write(`unknown target ${which}; one of ${Object.keys(all).join(', ')}\n`);
      return 2;
    }
    process.stdout.write(all[which]);
    return 0;
  }
  const outRoot = argv.includes('--out') ? argv[argv.indexOf('--out') + 1] : undefined;
  if (argv.includes('--out') && (outRoot === undefined || outRoot.startsWith('--'))) {
    process.stderr.write('--out needs a directory\n');
    return 2;
  }
  const stale = [];
  for (const [key, rel] of Object.entries(TARGETS)) {
    const abs = join(outRoot ?? ROOT, rel);
    const next = all[key];
    const cur = existsSync(abs) ? readFileSync(abs, 'utf8').replace(/\r\n/g, '\n') : null;
    if (cur === next) continue;
    if (argv.includes('--check')) stale.push(rel);
    else {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, next);
      process.stdout.write(`wrote ${rel}\n`);
    }
  }
  if (stale.length > 0) {
    process.stderr.write(`stale generated docs (run node scripts/gen-docs.mjs): ${stale.join(', ')}\n`);
    return 1;
  }
  return 0;
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  main(process.argv.slice(2)).then((code) => {
    process.exitCode = code;
  }, (e) => {
    process.stderr.write(`gen-docs: ${e instanceof Error ? e.stack ?? e.message : String(e)}\n`);
    process.exitCode = 1;
  });
}
