#compdef jevcode
# zsh completion for jevcode — generated by scripts/gen-docs.mjs from src/cli/args.ts; do not edit by hand
# install: jevcode completion zsh > ~/.zsh/completions/_jevcode  (with fpath+=~/.zsh/completions)

_jevcode_runs() {
  local runs="${JEVCODE_HOME:-$HOME/.jevcode}/runs"
  [[ -d "$runs" ]] && _values "run id" ${runs}/*(N:t)
}

_jevcode() {
  local -a commands
  commands=(
    'chat:interactive session'
    'run:run one task'
    'config:print the resolved configuration'
    'bench:run the benchmark suites'
    'perf:run the performance gates'
    'login:store an API key'
    'logout:remove a stored API key'
    'sessions:list or maintain sessions'
    'models:browse the model catalogue'
    'import:import memory and workflows from other agents'
    'agents:list the agents of a run'
    'doctor:check this machine and print one fix per problem'
    'report:write a support bundle'
    'why:explain a Jev decision'
    'calibration:reliability report'
    'completion:print a completion script'
    'upgrade:upgrade jevcode'
  )
  _arguments -C \
    '1:command:->cmd' \
    '*::arg:->args'
  case "$state" in
    cmd) _describe -t commands "jevcode command" commands ;;
    args)
      case "${words[1]}" in
        chat)
          _arguments \
            '--provider[generator provider (models: filter the catalogue to one provider)]:provider:(anthropic openrouter openai gemini xai fireworks meta)' \
            '--model[generator model id]:id:' \
            '--api-key[generator API key (prefer the env var)]:key:' \
            '--base-url[generator base URL]:url:' \
            '--temperature[generator temperature (unset = not sent)]:t:' \
            '--max-tokens[generator max output tokens]:n:' \
            '--jev-base-url[decider (Jev) base URL]:url:' \
            '--jev-api-key[decider API key (prefer the env var)]:key:' \
            '--jev-model[decider model id (dated id pins it)]:id:' \
            '--jev-provider[Jev provider (default auto: typesafe when TYPESAFE_API_KEY is set, else openrouter)]:jev-provider:(auto typesafe openrouter)' \
            '--spend-cap[run spend cap in USD (bench: total for the bench)]:usd:' \
            '--max-steps[max steps per run]:n:' \
            '--max-wall[max wall time per run, e.g. 30m, 7h30m, 90s]:dur:' \
            '--max-replans[max replans per run]:n:' \
            '--complete-threshold[completion probability threshold]:p:' \
            '--impossible-threshold[task-impossible probability threshold]:p:' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--extra-env-file[an additional .env file whose keys are read as a fallback]:<path>:_files' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--sandbox[sandbox profile]:sandbox:(auto seatbelt none)' \
            '--no-network[deny network to sandboxed commands]' \
            '--plain[plain line renderer instead of the TUI (readline composer on a TTY; models/import/agents: the numbered list)]' \
            '--theme[colour theme (no auto-detect)]:theme:(dark light daltonized ansi)' \
            '--fps[render frames per second, 5..30 (default 30; 15 over SSH); fixed at launch]:n:' \
            '--render-mode[Ink render mode (default standard); fixed at launch]:render-mode:(standard incremental)' \
            '--renderer[renderer (default classic); fullscreen pins the header on the alternate screen (needs 18 rows / 40 cols); fixed at launch]:renderer:(classic fullscreen)' \
            '--fullscreen[shorthand for --renderer fullscreen]' \
            '--ascii[ASCII glyphs (auto on TERM=dumb, TERM=linux, non-UTF-8 locale); fixed at launch]' \
            '--title[set the terminal title (OSC 2)]' \
            '--screen-reader[screen-reader mode (numbered prompts, no bars; implies --plain on a pipe); fixed at launch]' \
            '--no-animation[reduced motion: static spinner, 1 Hz clock (default on with --screen-reader)]' \
            '--notify[terminal notification (BEL / OSC) when a review waits or a run ends]' \
            '--osc52[allow clipboard writes through OSC 52 (write only)]' \
            '--no-history[do not persist composer history to ~/.jevcode/history.jsonl]' \
            '--no-input[no interactive renderer; every prompt takes its safe default (run only: needs a task)]' \
            '--trust-workspace[trust the workspace (AGENTS.md, ./.env, jevcode.json) without the prompt (scripts)]:dir:_files -/' \
            '--no-budget-warnings[mute budget toasts and the bell (items and JSON events stay)]' \
            '--allow-secret-mention[allow @-mentions of denylisted secret files after a per-mention y/N]' \
            '--no-color[disable colour (same as NO_COLOR)]' \
            '--exit-code[session exit code: always 0 (default) or the last run’s code]:exit-code:(zero last-run)' \
            '--keybindings[keybindings file (default ${XDG_CONFIG_HOME:-~/.config}/jevcode/keybindings.json)]:file:' \
            '--log[log file (default <runDir>/jevcode.log; JEVCODE_TRACE=<file> is the same at level trace)]:file:' \
            '--log-level[log level (default info; file only, keys never appear in logs)]:log-level:(error warn info debug trace)' \
            '--verbose[same as --log-level debug (decisions, hashes, latencies, checkpoint timings to the file only)]' \
            '--session-spend-cap[session spend cap in USD (default 5 × the run cap); none = uncapped]:usd|none:' \
            '--allow-unpriced[run an unpriced generator model under a token cap instead of refusing]' \
            '--max-generator-tokens[generator token cap under --allow-unpriced (default spend cap / 15 × 1e6)]:n:' \
            '--update-notify[post-run update check through a detached jevcode upgrade --check]' \
            '--continue[continue the most recently used session in this workspace]' \
            '--resume[chat/run: continue a run by id, or a session by exact title or unique prefix; bench: resume <bench-id>; import: continue a partly-applied import by its id]:run id:_jevcode_runs' \
            '--force[with --resume/--continue: resume a run whose stopReason is complete instead of seeding a follow-up]' \
            '--list-sessions[print the sessions of this workspace and exit]' \
            '--mode[engine mode (default llm-jev): jev-only (Jev alone, no generating LLM), jev-on (Jev + the code model), jev-off (generator only), llm-jev (candidate patches, tests verify, Jev arbitrates)]:mode:(jev-only jev-on jev-off llm-jev)' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--force-takeback[with --resume: re-take a run a peer claimed (bumps the claim epoch); an ordinary resume never does]' \
            '--split[split the task across agents (default off; orchestrate.split)]:split:(off auto ask)' \
            '--max-agents[the most agents one split may start (orchestrate.maxAgents)]:n:' \
            '--yes-split[with --split ask: accept the proposed manifest without the confirm]' \
            '--no-wait[never wait for an agent slot: refuse rather than queue (orchestrate.agentWaitCeilingMs)]' \
            '--no-memory[do not read the project and user memory files into the run]' \
            '--no-import[never offer to import from the other coding agents on this machine]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        run)
          _arguments \
            '--provider[generator provider (models: filter the catalogue to one provider)]:provider:(anthropic openrouter openai gemini xai fireworks meta)' \
            '--model[generator model id]:id:' \
            '--api-key[generator API key (prefer the env var)]:key:' \
            '--base-url[generator base URL]:url:' \
            '--temperature[generator temperature (unset = not sent)]:t:' \
            '--max-tokens[generator max output tokens]:n:' \
            '--jev-base-url[decider (Jev) base URL]:url:' \
            '--jev-api-key[decider API key (prefer the env var)]:key:' \
            '--jev-model[decider model id (dated id pins it)]:id:' \
            '--jev-provider[Jev provider (default auto: typesafe when TYPESAFE_API_KEY is set, else openrouter)]:jev-provider:(auto typesafe openrouter)' \
            '--spend-cap[run spend cap in USD (bench: total for the bench)]:usd:' \
            '--max-steps[max steps per run]:n:' \
            '--max-wall[max wall time per run, e.g. 30m, 7h30m, 90s]:dur:' \
            '--max-replans[max replans per run]:n:' \
            '--complete-threshold[completion probability threshold]:p:' \
            '--impossible-threshold[task-impossible probability threshold]:p:' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--extra-env-file[an additional .env file whose keys are read as a fallback]:<path>:_files' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--sandbox[sandbox profile]:sandbox:(auto seatbelt none)' \
            '--no-network[deny network to sandboxed commands]' \
            '--plain[plain line renderer instead of the TUI (readline composer on a TTY; models/import/agents: the numbered list)]' \
            '--theme[colour theme (no auto-detect)]:theme:(dark light daltonized ansi)' \
            '--fps[render frames per second, 5..30 (default 30; 15 over SSH); fixed at launch]:n:' \
            '--render-mode[Ink render mode (default standard); fixed at launch]:render-mode:(standard incremental)' \
            '--renderer[renderer (default classic); fullscreen pins the header on the alternate screen (needs 18 rows / 40 cols); fixed at launch]:renderer:(classic fullscreen)' \
            '--fullscreen[shorthand for --renderer fullscreen]' \
            '--ascii[ASCII glyphs (auto on TERM=dumb, TERM=linux, non-UTF-8 locale); fixed at launch]' \
            '--title[set the terminal title (OSC 2)]' \
            '--screen-reader[screen-reader mode (numbered prompts, no bars; implies --plain on a pipe); fixed at launch]' \
            '--no-animation[reduced motion: static spinner, 1 Hz clock (default on with --screen-reader)]' \
            '--notify[terminal notification (BEL / OSC) when a review waits or a run ends]' \
            '--osc52[allow clipboard writes through OSC 52 (write only)]' \
            '--no-history[do not persist composer history to ~/.jevcode/history.jsonl]' \
            '--no-input[no interactive renderer; every prompt takes its safe default (run only: needs a task)]' \
            '--trust-workspace[trust the workspace (AGENTS.md, ./.env, jevcode.json) without the prompt (scripts)]:dir:_files -/' \
            '--no-budget-warnings[mute budget toasts and the bell (items and JSON events stay)]' \
            '--allow-secret-mention[allow @-mentions of denylisted secret files after a per-mention y/N]' \
            '--no-color[disable colour (same as NO_COLOR)]' \
            '--exit-code[session exit code: always 0 (default) or the last run’s code]:exit-code:(zero last-run)' \
            '--keybindings[keybindings file (default ${XDG_CONFIG_HOME:-~/.config}/jevcode/keybindings.json)]:file:' \
            '--log[log file (default <runDir>/jevcode.log; JEVCODE_TRACE=<file> is the same at level trace)]:file:' \
            '--log-level[log level (default info; file only, keys never appear in logs)]:log-level:(error warn info debug trace)' \
            '--verbose[same as --log-level debug (decisions, hashes, latencies, checkpoint timings to the file only)]' \
            '--session-spend-cap[session spend cap in USD (default 5 × the run cap); none = uncapped]:usd|none:' \
            '--allow-unpriced[run an unpriced generator model under a token cap instead of refusing]' \
            '--max-generator-tokens[generator token cap under --allow-unpriced (default spend cap / 15 × 1e6)]:n:' \
            '--update-notify[post-run update check through a detached jevcode upgrade --check]' \
            '--continue[continue the most recently used session in this workspace]' \
            '--resume[chat/run: continue a run by id, or a session by exact title or unique prefix; bench: resume <bench-id>; import: continue a partly-applied import by its id]:run id:_jevcode_runs' \
            '--force[with --resume/--continue: resume a run whose stopReason is complete instead of seeding a follow-up]' \
            '--list-sessions[print the sessions of this workspace and exit]' \
            '--task-file[read the task text from a file]:<path>:_files' \
            '--mode[engine mode (default llm-jev): jev-only (Jev alone, no generating LLM), jev-on (Jev + the code model), jev-off (generator only), llm-jev (candidate patches, tests verify, Jev arbitrates)]:mode:(jev-only jev-on jev-off llm-jev)' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--force-takeback[with --resume: re-take a run a peer claimed (bumps the claim epoch); an ordinary resume never does]' \
            '--split[split the task across agents (default off; orchestrate.split)]:split:(off auto ask)' \
            '--max-agents[the most agents one split may start (orchestrate.maxAgents)]:n:' \
            '--yes-split[with --split ask: accept the proposed manifest without the confirm]' \
            '--no-wait[never wait for an agent slot: refuse rather than queue (orchestrate.agentWaitCeilingMs)]' \
            '--no-memory[do not read the project and user memory files into the run]' \
            '--no-import[never offer to import from the other coding agents on this machine]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]' \
            '*:task text:'
          ;;
        config)
          _arguments \
            '--provider[generator provider (models: filter the catalogue to one provider)]:provider:(anthropic openrouter openai gemini xai fireworks meta)' \
            '--model[generator model id]:id:' \
            '--api-key[generator API key (prefer the env var)]:key:' \
            '--base-url[generator base URL]:url:' \
            '--temperature[generator temperature (unset = not sent)]:t:' \
            '--max-tokens[generator max output tokens]:n:' \
            '--jev-base-url[decider (Jev) base URL]:url:' \
            '--jev-api-key[decider API key (prefer the env var)]:key:' \
            '--jev-model[decider model id (dated id pins it)]:id:' \
            '--jev-provider[Jev provider (default auto: typesafe when TYPESAFE_API_KEY is set, else openrouter)]:jev-provider:(auto typesafe openrouter)' \
            '--spend-cap[run spend cap in USD (bench: total for the bench)]:usd:' \
            '--max-steps[max steps per run]:n:' \
            '--max-wall[max wall time per run, e.g. 30m, 7h30m, 90s]:dur:' \
            '--max-replans[max replans per run]:n:' \
            '--complete-threshold[completion probability threshold]:p:' \
            '--impossible-threshold[task-impossible probability threshold]:p:' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--extra-env-file[an additional .env file whose keys are read as a fallback]:<path>:_files' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--sandbox[sandbox profile]:sandbox:(auto seatbelt none)' \
            '--no-network[deny network to sandboxed commands]' \
            '--plain[plain line renderer instead of the TUI (readline composer on a TTY; models/import/agents: the numbered list)]' \
            '--theme[colour theme (no auto-detect)]:theme:(dark light daltonized ansi)' \
            '--fps[render frames per second, 5..30 (default 30; 15 over SSH); fixed at launch]:n:' \
            '--render-mode[Ink render mode (default standard); fixed at launch]:render-mode:(standard incremental)' \
            '--renderer[renderer (default classic); fullscreen pins the header on the alternate screen (needs 18 rows / 40 cols); fixed at launch]:renderer:(classic fullscreen)' \
            '--fullscreen[shorthand for --renderer fullscreen]' \
            '--ascii[ASCII glyphs (auto on TERM=dumb, TERM=linux, non-UTF-8 locale); fixed at launch]' \
            '--title[set the terminal title (OSC 2)]' \
            '--screen-reader[screen-reader mode (numbered prompts, no bars; implies --plain on a pipe); fixed at launch]' \
            '--no-animation[reduced motion: static spinner, 1 Hz clock (default on with --screen-reader)]' \
            '--notify[terminal notification (BEL / OSC) when a review waits or a run ends]' \
            '--osc52[allow clipboard writes through OSC 52 (write only)]' \
            '--no-history[do not persist composer history to ~/.jevcode/history.jsonl]' \
            '--no-input[no interactive renderer; every prompt takes its safe default (run only: needs a task)]' \
            '--trust-workspace[trust the workspace (AGENTS.md, ./.env, jevcode.json) without the prompt (scripts)]:dir:_files -/' \
            '--no-budget-warnings[mute budget toasts and the bell (items and JSON events stay)]' \
            '--allow-secret-mention[allow @-mentions of denylisted secret files after a per-mention y/N]' \
            '--no-color[disable colour (same as NO_COLOR)]' \
            '--exit-code[session exit code: always 0 (default) or the last run’s code]:exit-code:(zero last-run)' \
            '--keybindings[keybindings file (default ${XDG_CONFIG_HOME:-~/.config}/jevcode/keybindings.json)]:file:' \
            '--log[log file (default <runDir>/jevcode.log; JEVCODE_TRACE=<file> is the same at level trace)]:file:' \
            '--log-level[log level (default info; file only, keys never appear in logs)]:log-level:(error warn info debug trace)' \
            '--verbose[same as --log-level debug (decisions, hashes, latencies, checkpoint timings to the file only)]' \
            '--session-spend-cap[session spend cap in USD (default 5 × the run cap); none = uncapped]:usd|none:' \
            '--allow-unpriced[run an unpriced generator model under a token cap instead of refusing]' \
            '--max-generator-tokens[generator token cap under --allow-unpriced (default spend cap / 15 × 1e6)]:n:' \
            '--update-notify[post-run update check through a detached jevcode upgrade --check]' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--all[config: include the hidden bookkeeping rows (seen.*); sessions who: include sessions gone more than 10 minutes and ignored devices]' \
            '--no-memory[do not read the project and user memory files into the run]' \
            '--no-import[never offer to import from the other coding agents on this machine]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        bench)
          _arguments \
            '--provider[generator provider (models: filter the catalogue to one provider)]:provider:(anthropic openrouter openai gemini xai fireworks meta)' \
            '--model[generator model id]:id:' \
            '--api-key[generator API key (prefer the env var)]:key:' \
            '--base-url[generator base URL]:url:' \
            '--temperature[generator temperature (unset = not sent)]:t:' \
            '--max-tokens[generator max output tokens]:n:' \
            '--jev-base-url[decider (Jev) base URL]:url:' \
            '--jev-api-key[decider API key (prefer the env var)]:key:' \
            '--jev-model[decider model id (dated id pins it)]:id:' \
            '--jev-provider[Jev provider (default auto: typesafe when TYPESAFE_API_KEY is set, else openrouter)]:jev-provider:(auto typesafe openrouter)' \
            '--spend-cap[run spend cap in USD (bench: total for the bench)]:usd:' \
            '--max-steps[max steps per run]:n:' \
            '--max-wall[max wall time per run, e.g. 30m, 7h30m, 90s]:dur:' \
            '--max-replans[max replans per run]:n:' \
            '--complete-threshold[completion probability threshold]:p:' \
            '--impossible-threshold[task-impossible probability threshold]:p:' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--extra-env-file[an additional .env file whose keys are read as a fallback]:<path>:_files' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--sandbox[sandbox profile]:sandbox:(auto seatbelt none)' \
            '--no-network[deny network to sandboxed commands]' \
            '--plain[plain line renderer instead of the TUI (readline composer on a TTY; models/import/agents: the numbered list)]' \
            '--resume[chat/run: continue a run by id, or a session by exact title or unique prefix; bench: resume <bench-id>; import: continue a partly-applied import by its id]:run id:_jevcode_runs' \
            '--suite[benchmark suite (quixbugs/ladder: the jev-only difficulty ladder)]:suite:(swebench terminal-bench quixbugs ladder all)' \
            '--tasks[number of tasks]:n:' \
            '--task-id[specific task ids]:id[,id...]:' \
            '--conditions[conditions to run (when omitted: the jev-on and jev-off arms)]:jev-on,jev-off[,jev-only,llm-jev,llm-sieve,jev-off-tuned,jev-on-next,jev-on-next-nofast]:' \
            '--concurrency[parallel runs]:n:' \
            '--live[use the real generator and Jev (requires --spend-cap)]' \
            '--task-spend-cap[per-run spend cap (default 2.00)]:usd:' \
            '--allow-model-alias[allow an undated --jev-model]' \
            '--archive-runs[copy each run'\''s records (steps/decisions/jev/generator.jsonl, run.json, state.json, patch) gzipped into <results>/runs/<runId>/]' \
            '--quick[the M16 quick preset (docs/LLM-LOOP-DESIGN.md §3.5): the five Ring-2 tasks, --concurrency 3, replay by default and --spend-cap 0.05 as DEFAULTS that never override an explicit flag]' \
            '--out[bench: results dir; perf: results file; report: bundle dir (default ~/.jevcode/reports/<id>/)]:<path>:_files' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        perf)
          _arguments \
            '--provider[generator provider (models: filter the catalogue to one provider)]:provider:(anthropic openrouter openai gemini xai fireworks meta)' \
            '--model[generator model id]:id:' \
            '--api-key[generator API key (prefer the env var)]:key:' \
            '--base-url[generator base URL]:url:' \
            '--temperature[generator temperature (unset = not sent)]:t:' \
            '--max-tokens[generator max output tokens]:n:' \
            '--jev-base-url[decider (Jev) base URL]:url:' \
            '--jev-api-key[decider API key (prefer the env var)]:key:' \
            '--jev-model[decider model id (dated id pins it)]:id:' \
            '--jev-provider[Jev provider (default auto: typesafe when TYPESAFE_API_KEY is set, else openrouter)]:jev-provider:(auto typesafe openrouter)' \
            '--spend-cap[run spend cap in USD (bench: total for the bench)]:usd:' \
            '--max-steps[max steps per run]:n:' \
            '--max-wall[max wall time per run, e.g. 30m, 7h30m, 90s]:dur:' \
            '--max-replans[max replans per run]:n:' \
            '--complete-threshold[completion probability threshold]:p:' \
            '--impossible-threshold[task-impossible probability threshold]:p:' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--extra-env-file[an additional .env file whose keys are read as a fallback]:<path>:_files' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--sandbox[sandbox profile]:sandbox:(auto seatbelt none)' \
            '--no-network[deny network to sandboxed commands]' \
            '--plain[plain line renderer instead of the TUI (readline composer on a TTY; models/import/agents: the numbered list)]' \
            '--live[use the real generator and Jev (requires --spend-cap)]' \
            '--out[bench: results dir; perf: results file; report: bundle dir (default ~/.jevcode/reports/<id>/)]:<path>:_files' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        login)
          _arguments \
            '--provider[generator provider (models: filter the catalogue to one provider)]:provider:(anthropic openrouter openai gemini xai fireworks meta)' \
            '--jev-provider[Jev provider (default auto: typesafe when TYPESAFE_API_KEY is set, else openrouter)]:jev-provider:(typesafe openrouter)' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--key-stdin[read one OpenRouter key from the first stdin line: it serves Jev and the code model (pipes)]' \
            '--generator-key-stdin[read the generator key from the first stdin line (pipes)]' \
            '--jev-key-stdin[read the Jev key from stdin (the next line)]' \
            '--status[print which keys are set and where they come from (fingerprints only)]' \
            '--verify[verify the saved keys: one priced Jev decision (~$0.00002), one 1-token code-model completion (~$0.000002), the key info ($0)]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        logout)
          _arguments \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--generator[remove the saved generator key]' \
            '--jev[remove the saved Jev key]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        sessions)
          _arguments \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--all[config: include the hidden bookkeeping rows (seen.*); sessions who: include sessions gone more than 10 minutes and ignored devices]' \
            '--device[with sessions gc: the device to remove, resolved by walking the disk to 1,024 devices (never through the 16-device fold cap)]:label:' \
            '--rotate[with sessions pair: take a new device id and key, invalidating the old one everywhere]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        models)
          _arguments \
            '--provider[generator provider (models: filter the catalogue to one provider)]:provider:(anthropic openrouter openai gemini xai fireworks meta)' \
            '--plain[plain line renderer instead of the TUI (readline composer on a TTY; models/import/agents: the numbered list)]' \
            '--ascii[ASCII glyphs (auto on TERM=dumb, TERM=linux, non-UTF-8 locale); fixed at launch]' \
            '--screen-reader[screen-reader mode (numbered prompts, no bars; implies --plain on a pipe); fixed at launch]' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        import)
          _arguments \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--plain[plain line renderer instead of the TUI (readline composer on a TTY; models/import/agents: the numbered list)]' \
            '--ascii[ASCII glyphs (auto on TERM=dumb, TERM=linux, non-UTF-8 locale); fixed at launch]' \
            '--screen-reader[screen-reader mode (numbered prompts, no bars; implies --plain on a pipe); fixed at launch]' \
            '--resume[chat/run: continue a run by id, or a session by exact title or unique prefix; bench: resume <bench-id>; import: continue a partly-applied import by its id]:run id:_jevcode_runs' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--dry-run[plan and report only — nothing is written]' \
            '--yes[apply the non-credential rows without the review step (a credential row always needs a terminal)]' \
            '--scope[where the imported rows are written (default both)]:scope:(user project both)' \
            '--undo[restore the files one earlier import replaced]:importId:' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        agents)
          _arguments \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--plain[plain line renderer instead of the TUI (readline composer on a TTY; models/import/agents: the numbered list)]' \
            '--ascii[ASCII glyphs (auto on TERM=dumb, TERM=linux, non-UTF-8 locale); fixed at launch]' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        doctor)
          _arguments \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        report)
          _arguments \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--out[bench: results dir; perf: results file; report: bundle dir (default ~/.jevcode/reports/<id>/)]:<path>:_files' \
            '--include-requests[include the redacted jev.jsonl request bodies in the bundle]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        why)
          _arguments \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        calibration)
          _arguments \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--config[config file (default: ./jevcode.json, else ${XDG_CONFIG_HOME:-~/.config}/jevcode/config.json)]:<file>:_files' \
            '--json[chat/run: NDJSON event stream on stdout (non-interactive; --json=verbose adds status events); config/sessions/models/import/agents/why/calibration: JSON output]' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        completion)
          _arguments \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
        upgrade)
          _arguments \
            '--check[only report whether a newer version exists (2 s registry timeout)]' \
            '--method[package manager to upgrade with (default: detected from the install path)]:method:(npm brew bun pnpm yarn)' \
            '--help[show usage]' \
            '--version[print the version (--json: name, version, node, ink, react, bundle)]'
          ;;
      esac ;;
  esac
}

_jevcode "$@"
