# bash completion for jevcode — generated by scripts/gen-docs.mjs from src/cli/args.ts; do not edit by hand
# install: jevcode completion bash > ~/.local/share/bash-completion/completions/jevcode

_jevcode() {
  local cur prev cmd words
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  cmd=""
  local i
  for ((i = 1; i < COMP_CWORD; i++)); do
    case "${COMP_WORDS[i]}" in
      run|config|bench|perf) cmd="${COMP_WORDS[i]}"; break ;;
    esac
  done
  case "$prev" in
    --resume)
      local runs="${JEVCODE_HOME:-$HOME/.jevcode}/runs"
      [ -d "$runs" ] && COMPREPLY=( $(compgen -W "$(ls "$runs" 2>/dev/null)" -- "$cur") )
      return 0 ;;
    --provider) COMPREPLY=( $(compgen -W 'anthropic openrouter' -- "$cur") ); return 0 ;;
    --sandbox) COMPREPLY=( $(compgen -W 'auto seatbelt none' -- "$cur") ); return 0 ;;
    --mode) COMPREPLY=( $(compgen -W 'jev-on jev-off jev-only' -- "$cur") ); return 0 ;;
    --suite) COMPREPLY=( $(compgen -W 'swebench terminal-bench quixbugs ladder all' -- "$cur") ); return 0 ;;
    --task-file|--config|--out) COMPREPLY=( $(compgen -f -- "$cur") ); return 0 ;;
    --workspace|--runs-dir|--open-assist-path) COMPREPLY=( $(compgen -d -- "$cur") ); return 0 ;;
  esac
  if [ -z "$cmd" ]; then
    COMPREPLY=( $(compgen -W 'run config bench perf --help --version' -- "$cur") )
    return 0
  fi
  case "$cmd" in
    run) COMPREPLY=( $(compgen -W '--provider --model --api-key --base-url --temperature --max-tokens --jev-base-url --jev-api-key --jev-model --spend-cap --max-steps --max-wall --max-replans --complete-threshold --impossible-threshold --workspace --runs-dir --open-assist-path --config --sandbox --no-network --plain --task-file --resume --force --mode --help --version' -- "$cur") ) ;;
    config) COMPREPLY=( $(compgen -W '--provider --model --api-key --base-url --temperature --max-tokens --jev-base-url --jev-api-key --jev-model --spend-cap --max-steps --max-wall --max-replans --complete-threshold --impossible-threshold --workspace --runs-dir --open-assist-path --config --sandbox --no-network --plain --json --help --version' -- "$cur") ) ;;
    bench) COMPREPLY=( $(compgen -W '--provider --model --api-key --base-url --temperature --max-tokens --jev-base-url --jev-api-key --jev-model --spend-cap --max-steps --max-wall --max-replans --complete-threshold --impossible-threshold --workspace --runs-dir --open-assist-path --config --sandbox --no-network --plain --resume --suite --tasks --task-id --conditions --concurrency --live --task-spend-cap --allow-model-alias --out --help --version' -- "$cur") ) ;;
    perf) COMPREPLY=( $(compgen -W '--provider --model --api-key --base-url --temperature --max-tokens --jev-base-url --jev-api-key --jev-model --spend-cap --max-steps --max-wall --max-replans --complete-threshold --impossible-threshold --workspace --runs-dir --open-assist-path --config --sandbox --no-network --plain --live --out --help --version' -- "$cur") ) ;;
  esac
  return 0
}
complete -F _jevcode jevcode
