#compdef jevcode
# zsh completion for jevcode — generated by scripts/gen-docs.mjs from src/cli/args.ts; do not edit by hand
# install: jevcode completion zsh > ~/.zsh/completions/_jevcode  (with fpath+=~/.zsh/completions)

_jevcode_runs() {
  local runs="${JEVCODE_HOME:-$HOME/.jevcode}/runs"
  [[ -d "$runs" ]] && _values "run id" ${runs}/*(N:t)
}

_jevcode() {
  local -a commands
  commands=(
    'run:run one task'
    'config:print the resolved configuration'
    'bench:run the benchmark suites'
    'perf:run the performance gates'
  )
  _arguments -C \
    '1:command:->cmd' \
    '*::arg:->args'
  case "$state" in
    cmd) _describe -t commands "jevcode command" commands ;;
    args)
      case "${words[1]}" in
        run)
          _arguments \
            '--provider[generator provider]:provider:(anthropic openrouter)' \
            '--model[generator model id]:id:' \
            '--api-key[generator API key (prefer the env var)]:key:' \
            '--base-url[generator base URL]:url:' \
            '--temperature[generator temperature (unset = not sent)]:t:' \
            '--max-tokens[generator max output tokens]:n:' \
            '--jev-base-url[decider (Jev) base URL]:url:' \
            '--jev-api-key[decider API key (prefer the env var)]:key:' \
            '--jev-model[decider model id (dated id pins it)]:id:' \
            '--spend-cap[spend cap in USD (bench: total for the bench)]:usd:' \
            '--max-steps[max steps per run]:n:' \
            '--max-wall[max wall time per run, e.g. 30m, 7h30m, 90s]:dur:' \
            '--max-replans[max replans per run]:n:' \
            '--complete-threshold[completion probability threshold]:p:' \
            '--impossible-threshold[task-impossible probability threshold]:p:' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--open-assist-path[Open Assist checkout whose .env is a fallback]:<dir>:_files' \
            '--config[config file (default: ./jevcode.json, else ~/.config/jevcode/config.json)]:<file>:_files' \
            '--sandbox[sandbox profile]:sandbox:(auto seatbelt none)' \
            '--no-network[deny network to sandboxed commands]' \
            '--plain[plain line renderer instead of the TUI]' \
            '--task-file[read the task text from a file]:<path>:_files' \
            '--resume[run: resume <run-id>; bench: resume <bench-id>]:run id:_jevcode_runs' \
            '--force[with --resume: resume a run whose stopReason is complete]' \
            '--mode[engine mode: jev-on (default), jev-off (generator only), jev-only (no generating LLM)]:mode:(jev-on jev-off jev-only)' \
            '--help[show usage]' \
            '--version[print the version]' \
            '*:task text:'
          ;;
        config)
          _arguments \
            '--provider[generator provider]:provider:(anthropic openrouter)' \
            '--model[generator model id]:id:' \
            '--api-key[generator API key (prefer the env var)]:key:' \
            '--base-url[generator base URL]:url:' \
            '--temperature[generator temperature (unset = not sent)]:t:' \
            '--max-tokens[generator max output tokens]:n:' \
            '--jev-base-url[decider (Jev) base URL]:url:' \
            '--jev-api-key[decider API key (prefer the env var)]:key:' \
            '--jev-model[decider model id (dated id pins it)]:id:' \
            '--spend-cap[spend cap in USD (bench: total for the bench)]:usd:' \
            '--max-steps[max steps per run]:n:' \
            '--max-wall[max wall time per run, e.g. 30m, 7h30m, 90s]:dur:' \
            '--max-replans[max replans per run]:n:' \
            '--complete-threshold[completion probability threshold]:p:' \
            '--impossible-threshold[task-impossible probability threshold]:p:' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--open-assist-path[Open Assist checkout whose .env is a fallback]:<dir>:_files' \
            '--config[config file (default: ./jevcode.json, else ~/.config/jevcode/config.json)]:<file>:_files' \
            '--sandbox[sandbox profile]:sandbox:(auto seatbelt none)' \
            '--no-network[deny network to sandboxed commands]' \
            '--plain[plain line renderer instead of the TUI]' \
            '--json[print the resolved table as JSON]' \
            '--help[show usage]' \
            '--version[print the version]'
          ;;
        bench)
          _arguments \
            '--provider[generator provider]:provider:(anthropic openrouter)' \
            '--model[generator model id]:id:' \
            '--api-key[generator API key (prefer the env var)]:key:' \
            '--base-url[generator base URL]:url:' \
            '--temperature[generator temperature (unset = not sent)]:t:' \
            '--max-tokens[generator max output tokens]:n:' \
            '--jev-base-url[decider (Jev) base URL]:url:' \
            '--jev-api-key[decider API key (prefer the env var)]:key:' \
            '--jev-model[decider model id (dated id pins it)]:id:' \
            '--spend-cap[spend cap in USD (bench: total for the bench)]:usd:' \
            '--max-steps[max steps per run]:n:' \
            '--max-wall[max wall time per run, e.g. 30m, 7h30m, 90s]:dur:' \
            '--max-replans[max replans per run]:n:' \
            '--complete-threshold[completion probability threshold]:p:' \
            '--impossible-threshold[task-impossible probability threshold]:p:' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--open-assist-path[Open Assist checkout whose .env is a fallback]:<dir>:_files' \
            '--config[config file (default: ./jevcode.json, else ~/.config/jevcode/config.json)]:<file>:_files' \
            '--sandbox[sandbox profile]:sandbox:(auto seatbelt none)' \
            '--no-network[deny network to sandboxed commands]' \
            '--plain[plain line renderer instead of the TUI]' \
            '--resume[run: resume <run-id>; bench: resume <bench-id>]:run id:_jevcode_runs' \
            '--suite[benchmark suite (quixbugs/ladder: the jev-only difficulty ladder)]:suite:(swebench terminal-bench quixbugs ladder all)' \
            '--tasks[number of tasks]:n:' \
            '--task-id[specific task ids]:id[,id...]:' \
            '--conditions[conditions to run (default jev-on,jev-off)]:jev-on,jev-off[,jev-only]:' \
            '--concurrency[parallel runs]:n:' \
            '--live[use the real generator and Jev (requires --spend-cap)]' \
            '--task-spend-cap[per-run spend cap (default 2.00)]:usd:' \
            '--allow-model-alias[allow an undated --jev-model]' \
            '--out[bench: results dir; perf: results file]:<path>:_files' \
            '--help[show usage]' \
            '--version[print the version]'
          ;;
        perf)
          _arguments \
            '--provider[generator provider]:provider:(anthropic openrouter)' \
            '--model[generator model id]:id:' \
            '--api-key[generator API key (prefer the env var)]:key:' \
            '--base-url[generator base URL]:url:' \
            '--temperature[generator temperature (unset = not sent)]:t:' \
            '--max-tokens[generator max output tokens]:n:' \
            '--jev-base-url[decider (Jev) base URL]:url:' \
            '--jev-api-key[decider API key (prefer the env var)]:key:' \
            '--jev-model[decider model id (dated id pins it)]:id:' \
            '--spend-cap[spend cap in USD (bench: total for the bench)]:usd:' \
            '--max-steps[max steps per run]:n:' \
            '--max-wall[max wall time per run, e.g. 30m, 7h30m, 90s]:dur:' \
            '--max-replans[max replans per run]:n:' \
            '--complete-threshold[completion probability threshold]:p:' \
            '--impossible-threshold[task-impossible probability threshold]:p:' \
            '--workspace[workspace directory (default: cwd)]:<dir>:_files -/' \
            '--runs-dir[run directory root (default: ~/.jevcode/runs)]:<dir>:_files -/' \
            '--open-assist-path[Open Assist checkout whose .env is a fallback]:<dir>:_files' \
            '--config[config file (default: ./jevcode.json, else ~/.config/jevcode/config.json)]:<file>:_files' \
            '--sandbox[sandbox profile]:sandbox:(auto seatbelt none)' \
            '--no-network[deny network to sandboxed commands]' \
            '--plain[plain line renderer instead of the TUI]' \
            '--live[use the real generator and Jev (requires --spend-cap)]' \
            '--out[bench: results dir; perf: results file]:<path>:_files' \
            '--help[show usage]' \
            '--version[print the version]'
          ;;
      esac ;;
  esac
}

_jevcode "$@"
